// frontend/src/components/ui/connection-chip.tsx
import { CircleAlert, Loader, PlugZap, WifiOff } from 'lucide-react'
import { cn } from '@/lib/utils'

/**
 * ConnectionChip — persistent WebSocket state indicator. Sits in the
 * app shell so a player mid-combat can tell at a glance whether their
 * mutations are landing on the server. Responsive audit called out
 * that we lacked this — without it, silent WS drops just look like
 * a slow tracker.
 *
 * `dirty` piggybacks on the existing `persistence-warning` event —
 * shows a subtle warning even when the socket is technically live.
 */
type ConnectionStatus = 'connected' | 'reconnecting' | 'offline'

type ConnectionChipProps = {
  status: ConnectionStatus
  dirty?: boolean
  compact?: boolean
  className?: string
}

const STATUS_COPY: Record<ConnectionStatus, string> = {
  connected: 'Conectado',
  reconnecting: 'Reconectando…',
  offline: 'Offline',
}

function ConnectionChip({
  status,
  dirty = false,
  compact = false,
  className,
}: ConnectionChipProps) {
  const Icon =
    status === 'connected'
      ? dirty
        ? CircleAlert
        : PlugZap
      : status === 'reconnecting'
        ? Loader
        : WifiOff

  const tone =
    status === 'connected'
      ? dirty
        ? 'border-[color:var(--hp-hurt)]/60 bg-[color-mix(in_oklch,var(--hp-hurt)_10%,transparent)] text-[color:var(--hp-hurt)]'
        : 'border-[color:var(--hp-full)]/50 bg-[color-mix(in_oklch,var(--hp-full)_10%,transparent)] text-[color:var(--hp-full)]'
      : status === 'reconnecting'
        ? 'border-[color:var(--primary)]/60 bg-[color-mix(in_oklch,var(--primary)_10%,transparent)] text-[color:var(--primary)]'
        : 'border-[color:var(--hp-critical)]/70 bg-[color-mix(in_oklch,var(--hp-critical)_15%,transparent)] text-[color:var(--hp-critical)]'

  const label = dirty ? 'Alterações não salvas' : STATUS_COPY[status]

  return (
    <span
      role="status"
      data-slot="connection-chip"
      data-status={status}
      data-dirty={dirty ? 'true' : 'false'}
      aria-label={label}
      className={cn(
        'inline-flex items-center gap-1.5 rounded-full border px-2 py-0.5 text-xs font-medium',
        tone,
        className,
      )}
    >
      <Icon
        className={cn(
          'size-3.5',
          status === 'reconnecting' && 'animate-spin',
        )}
      />
      {!compact && <span>{label}</span>}
    </span>
  )
}

export { ConnectionChip }
export type { ConnectionStatus }

// frontend-solid/src/shared/ui/connection-chip.tsx
import { CircleAlert, Loader, PlugZap, WifiOff } from 'lucide-solid'
import { Dynamic } from 'solid-js/web'
import { cn } from '@/shared/lib/utils'

export type ConnectionStatus = 'connected' | 'reconnecting' | 'offline'

const STATUS_COPY: Record<ConnectionStatus, string> = {
  connected: 'Conectado',
  reconnecting: 'Reconectando…',
  offline: 'Offline',
}

/**
 * Live WebSocket state, in words. Without it a silent drop mid-combat just
 * looks like a slow tracker — the player has no way to tell that their hits
 * are landing nowhere.
 *
 * `dirty` rides the server's `persistence-warning`: the socket is up, but the
 * last mutation did not persist.
 *
 * @example <ConnectionChip status="reconnecting" dirty={false} />
 */
export function ConnectionChip(props: {
  status: ConnectionStatus
  dirty?: boolean
  class?: string
}) {
  const icon = () => {
    if (props.status === 'connected') return props.dirty ? CircleAlert : PlugZap
    return props.status === 'reconnecting' ? Loader : WifiOff
  }
  const tone = () => {
    if (props.status === 'connected') {
      return props.dirty
        ? 'border-amber-500/40 text-amber-300'
        : 'border-emerald-500/40 text-emerald-300'
    }
    return props.status === 'reconnecting'
      ? 'border-amber-500/40 text-amber-300'
      : 'border-destructive/50 text-red-300'
  }
  const label = () =>
    props.dirty && props.status === 'connected'
      ? 'Conectado · alterações não salvas'
      : STATUS_COPY[props.status]

  return (
    <span
      class={cn(
        'inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-widest',
        tone(),
        props.class,
      )}
      // role=status: the state CHANGES while the player is looking elsewhere,
      // and a drop is exactly what has to be announced.
      role="status"
    >
      <Dynamic
        component={icon()}
        aria-hidden="true"
        class={cn('size-3', props.status === 'reconnecting' && 'animate-spin')}
      />
      {label()}
    </span>
  )
}
