// frontend/src/shared/ui/popover.tsx
import * as React from "react"
import { Popover as PopoverPrimitive } from "radix-ui"

import { cn } from "@/shared/lib/utils"
import { useSceneContainer } from "@/shared/lib/scene-container"

function Popover({
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Root>) {
  return <PopoverPrimitive.Root data-slot="popover" {...props} />
}

function PopoverTrigger({
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Trigger>) {
  return <PopoverPrimitive.Trigger data-slot="popover-trigger" {...props} />
}

function PopoverContent({
  className,
  align = "center",
  sideOffset = 4,
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Content>) {
  // Portal into the current grimório scene (if any) so tokens are inherited.
  const container = useSceneContainer()
  return (
    <PopoverPrimitive.Portal container={container ?? undefined}>
      <PopoverPrimitive.Content
        data-slot="popover-content"
        align={align}
        sideOffset={sideOffset}
        className={cn(
          "z-50 w-72 origin-(--radix-popover-content-transform-origin) rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-hidden data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95 data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95",
          className
        )}
        {...props}
      />
    </PopoverPrimitive.Portal>
  )
}

function PopoverAnchor({
  ...props
}: React.ComponentProps<typeof PopoverPrimitive.Anchor>) {
  return <PopoverPrimitive.Anchor data-slot="popover-anchor" {...props} />
}

function PopoverHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="popover-header"
      className={cn("flex flex-col gap-1 text-sm", className)}
      {...props}
    />
  )
}

function PopoverTitle({ className, ...props }: React.ComponentProps<"h2">) {
  return (
    <div
      data-slot="popover-title"
      className={cn("font-medium", className)}
      {...props}
    />
  )
}

function PopoverDescription({
  className,
  ...props
}: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="popover-description"
      className={cn("text-muted-foreground", className)}
      {...props}
    />
  )
}

export {
  Popover,
  PopoverTrigger,
  PopoverContent,
  PopoverAnchor,
  PopoverHeader,
  PopoverTitle,
  PopoverDescription,
}

// frontend-solid/src/shared/ui/popover.tsx
import { Popover as KPopover } from '@kobalte/core/popover'
import { type ComponentProps, splitProps } from 'solid-js'
import { useSceneContainer } from '@/shared/lib/scene-container'
import { cn } from '@/shared/lib/utils'

/**
 * Popover on Kobalte. Radix's `data-[state=open]` becomes `data-[expanded]`;
 * placement is `placement="bottom"` rather than `side`/`align` pairs.
 *
 * @example
 * <Popover>
 *   <PopoverTrigger>Filtros</PopoverTrigger>
 *   <PopoverContent>…</PopoverContent>
 * </Popover>
 */
export const Popover = KPopover
export const PopoverTrigger = KPopover.Trigger
export const PopoverAnchor = KPopover.Anchor

export type PopoverContentProps = ComponentProps<typeof KPopover.Content> & {
  /** Portal target. Defaults to the enclosing grimório scene, else body. */
  mount?: Node
}

export function PopoverContent(props: PopoverContentProps) {
  const [local, rest] = splitProps(props, ['class', 'mount'])
  const scene = useSceneContainer()
  return (
    <KPopover.Portal mount={local.mount ?? scene() ?? undefined}>
      <KPopover.Content
        data-slot="popover-content"
        class={cn(
          'z-50 w-72 rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-hidden data-[closed]:animate-out data-[closed]:fade-out-0 data-[closed]:zoom-out-95 data-[expanded]:animate-in data-[expanded]:fade-in-0 data-[expanded]:zoom-in-95',
          local.class,
        )}
        {...rest}
      />
    </KPopover.Portal>
  )
}

export function PopoverHeader(props: ComponentProps<'div'>) {
  const [local, rest] = splitProps(props, ['class'])
  return <div data-slot="popover-header" class={cn('flex flex-col gap-1 text-sm', local.class)} {...rest} />
}

export function PopoverTitle(props: ComponentProps<typeof KPopover.Title>) {
  const [local, rest] = splitProps(props, ['class'])
  return <KPopover.Title data-slot="popover-title" class={cn('font-medium', local.class)} {...rest} />
}

export function PopoverDescription(props: ComponentProps<typeof KPopover.Description>) {
  const [local, rest] = splitProps(props, ['class'])
  return (
    <KPopover.Description
      data-slot="popover-description"
      class={cn('text-muted-foreground', local.class)}
      {...rest}
    />
  )
}
