// frontend/src/pages/characters/wizard/classe-step.tsx
import { ATTRIBUTE_KEYS, attributePresetForClass } from '@tormenta20/t20-data'
import { Button } from '@/shared/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/shared/ui/card'
import { ConfirmDialog } from '@/shared/ui/confirm-dialog'
import { Field, FieldDescription, FieldError, FieldLabel } from '@/shared/ui/field'
import { NumberInput } from '@/shared/ui/number-input'
import { ClassEntryRow } from '@/features/character-build/class-entry-row'
import { ClassTileGrid } from '@/features/character-build/class-picker'
import { ClassGrantPanel } from '@/features/character-build/grant-panels'
import {
  type FieldApi,
  useCreationWizard,
} from '@/features/character-build/creation-wizard-context'

export function ClasseStep() {
  const { form, options } = useCreationWizard()

  const applyPreset = (className: string) => {
    const preset = attributePresetForClass(className)
    if (!preset) return
    for (const attr of ATTRIBUTE_KEYS) form.setFieldValue(attr, preset[attr])
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-display tracking-wide">Classe</CardTitle>
      </CardHeader>
      <CardContent className="space-y-3">
        <form.Field name="classes" mode="array">
          {(classesField: FieldApi) => {
            const items = classesField.state.value as {
              className: string
              level: number
            }[]
            const primary = items[0]?.className ?? ''
            const arrayInvalid =
              classesField.state.meta.isTouched &&
              !classesField.state.meta.isValid
            const pickPrimary = (className: string) => {
              if (items.length === 0) {
                classesField.pushValue({ className, level: 1 })
              } else {
                // Replace via the array API (not setFieldValue on a nested
                // path) so the array Field re-renders and the tile selection
                // updates. Read the level from the live form state — the
                // captured `items` is stale w.r.t. the level input's edits.
                const level =
                  (form.state.values.classes[0]?.level as number) ?? 1
                classesField.replaceValue(0, { className, level })
              }
              applyPreset(className)
            }
            const addMulticlass = () => {
              const next =
                options.classes.find(
                  (c) => !items.some((it) => it.className === c),
                ) ?? options.classes[0]
              classesField.pushValue({ className: next, level: 1 })
            }
            return (
              <div className="lg:grid lg:grid-cols-[1.1fr_1fr] lg:gap-4">
                {/* Left: scrollable class catalog + level + multiclass */}
                <div className="space-y-3">
                  <div className="max-h-[min(320px,40vh)] overflow-y-auto p-1.5">
                    <ClassTileGrid
                      options={options.classes}
                      selected={primary}
                      onSelect={pickPrimary}
                    />
                  </div>
                  {items.length > 0 && (
                    <form.Field name="classes[0].level">
                      {(f: FieldApi) => (
                        <Field className="w-24">
                          <FieldLabel htmlFor={f.name}>Nível</FieldLabel>
                          <NumberInput
                            id={f.name}
                            min={1}
                            max={20}
                            value={f.state.value as number}
                            onChange={(v) => f.handleChange(v)}
                            onBlur={f.handleBlur}
                          />
                        </Field>
                      )}
                    </form.Field>
                  )}

                  {items.slice(1).map((_, j) => {
                    const i = j + 1
                    return (
                      <div
                        key={i}
                        className="space-y-2 rounded-md border border-dashed border-border p-2"
                      >
                        <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                          Classe adicional (avançado)
                        </p>
                        <ClassEntryRow
                          index={i}
                          classOptions={options.classes}
                          form={form}
                          onRemove={() => classesField.removeValue(i)}
                        />
                        <form.Subscribe
                          selector={(s: {
                            values: {
                              classes: { className: string; level: number }[]
                            }
                          }) =>
                            [
                              s.values.classes[i]?.className,
                              s.values.classes[i]?.level,
                            ] as const
                          }
                        >
                          {([className, level]: readonly [
                            string | undefined,
                            number | undefined,
                          ]) =>
                            className ? (
                              <ClassGrantPanel
                                className={className}
                                level={level ?? 1}
                              />
                            ) : null
                          }
                        </form.Subscribe>
                      </div>
                    )
                  })}

                  {items.length >= 1 && (
                    <ConfirmDialog
                      destructive={false}
                      title="Adicionar multiclasse?"
                      description="Multiclasse é adquirida em níveis mais altos via Poder de Multiclasse — não é padrão no nível 1. O preset de atributos usa apenas a primeira classe."
                      confirmLabel="Adicionar mesmo assim"
                      onConfirm={addMulticlass}
                      trigger={
                        <Button type="button" variant="outline" size="sm">
                          + Adicionar classe (multiclasse)
                        </Button>
                      }
                    />
                  )}

                  {arrayInvalid ? (
                    <FieldError errors={classesField.state.meta.errors} />
                  ) : !items.length ? (
                    <FieldDescription>Selecione uma classe.</FieldDescription>
                  ) : null}
                </div>

                {/* Right: pinned primary-class grant */}
                <div className="mt-3 lg:mt-0 lg:max-h-[min(420px,52vh)] lg:overflow-y-auto lg:pr-1">
                  <form.Subscribe
                    selector={(s: {
                      values: { classes: { className: string; level: number }[] }
                    }) =>
                      [
                        s.values.classes[0]?.className,
                        s.values.classes[0]?.level,
                      ] as const
                    }
                  >
                    {([className, level]: readonly [
                      string | undefined,
                      number | undefined,
                    ]) =>
                      className ? (
                        <ClassGrantPanel className={className} level={level ?? 1} />
                      ) : (
                        <p className="rounded-lg border border-dashed border-border p-4 text-center text-xs text-muted-foreground">
                          Selecione uma classe para ver os detalhes.
                        </p>
                      )
                    }
                  </form.Subscribe>
                </div>
              </div>
            )
          }}
        </form.Field>
      </CardContent>
    </Card>
  )
}

// frontend-solid/src/pages/characters/forge/classe-step.tsx
import { X } from 'lucide-solid'
import { Index, Show, createSignal } from 'solid-js'
import {
  type AttributeSpread,
  type ClassEntry,
  addClassEntry,
  attributeSpreadOf,
  classPresetSpread,
  removeClassEntry,
  setClassLevel,
  totalClassLevel,
} from '@/features/character-build/class-entries'
import { ClassTileGrid } from '@/features/character-build/class-picker'
import { useForge } from '@/features/character-build/forge-context'
import { ClassGrantLines, GrantBox } from '@/features/character-build/grant-panels'
import { Button } from '@/shared/ui/button'
import { ConfirmDialog } from '@/shared/ui/confirm-dialog'
import { NumberInput } from '@/shared/ui/number-input'

/**
 * Second step: the ofício. Same grammar as the lineage step — a grid of tiles,
 * the chosen ones detailed beside it — because a player should learn one way of
 * choosing and use it twice.
 *
 * Two rules of the table live here. Multiclasse is not a level-1 thing, so a
 * SECOND class is confirmed before it lands; and picking the first class fills
 * the suggested attribute spread, which it announces with an undo instead of
 * quietly overwriting whatever the player had typed.
 */
export function ClasseStep() {
  const { draft, options } = useForge()
  const [pendingMulticlass, setPendingMulticlass] = createSignal<string | null>(null)
  const [presetUndo, setPresetUndo] = createSignal<{
    className: string
    previous: AttributeSpread
  } | null>(null)

  const entries = () => draft.values.classes
  const chosenNames = () => entries().map((entry) => entry.className)

  /** Fill the class's suggested spread, remembering what it replaced. */
  const applyPreset = (className: string) => {
    const preset = classPresetSpread(className)
    if (!preset) return
    setPresetUndo({ className, previous: attributeSpreadOf(draft.values) })
    draft.patchValues(preset)
  }

  const undoPreset = () => {
    const undo = presetUndo()
    if (!undo) return
    draft.patchValues(undo.previous)
    setPresetUndo(null)
  }

  const addClass = (className: string) => {
    draft.setValue('classes', addClassEntry(entries(), className))
  }

  const toggle = (className: string) => {
    if (chosenNames().includes(className)) {
      draft.setValue('classes', removeClassEntry(entries(), className))
      return
    }
    if (entries().length === 0) {
      addClass(className)
      applyPreset(className)
      return
    }
    // Second class onward: ask first. The preset stays with the primary — a
    // multiclasse pick must not rewrite attributes chosen for the main class.
    setPendingMulticlass(className)
  }

  const setLevel = (className: string, level: number) => {
    draft.setValue('classes', setClassLevel(entries(), className, level))
  }

  return (
    <section class="flex min-h-0 flex-1 flex-col gap-3" aria-labelledby="forge-step-classe">
      <div class="flex flex-wrap items-baseline gap-x-3 gap-y-1">
        <h2
          id="forge-step-classe"
          class="font-heading text-lg uppercase tracking-[0.16em] text-grimorio-gold"
        >
          Escolha o ofício
        </h2>
        <Show
          when={entries().length > 1}
          fallback={
            <p class="text-xs text-muted-foreground">
              A primeira classe é a principal — ela semeia os PV e a sugestão de atributos.
            </p>
          }
        >
          <p class="text-xs text-muted-foreground">
            Nível total {totalClassLevel(entries())} · multiclasse
          </p>
        </Show>
      </div>

      <Show when={presetUndo()}>
        {(undo) => (
          <p class="flex flex-wrap items-center gap-2 rounded-md border border-grimorio-iron bg-muted/20 px-3 py-2 text-xs text-muted-foreground">
            Atributos preenchidos com a sugestão de {undo().className}.
            <Button type="button" variant="outline" size="sm" onClick={undoPreset}>
              Desfazer
            </Button>
          </p>
        )}
      </Show>

      <div class="grid gap-4 lg:min-h-0 lg:flex-1 lg:grid-cols-[1.15fr_1fr]">
        <div class="p-1 lg:min-h-0 lg:overflow-y-auto">
          <ClassTileGrid options={options.classes} value={chosenNames()} onToggle={toggle} />
        </div>

        <section
          aria-label="Classes escolhidas"
          class="space-y-2 lg:min-h-0 lg:overflow-y-auto lg:pr-1"
        >
          <Show
            when={entries().length > 0}
            fallback={
              <p class="rounded-lg border border-dashed border-grimorio-iron p-4 text-center text-xs text-muted-foreground">
                Escolha um ofício para ver o que ele concede.
              </p>
            }
          >
            {/* `Index`, not `For`: every keystroke in a level field produces a
                NEW entry object, and a reference-keyed For would tear the row
                down mid-typing — the field would lose focus after one digit. */}
            <Index each={entries()}>
              {(entry, i) => (
                <ChosenClass
                  entry={entry()}
                  isPrimary={i === 0}
                  onLevel={(level) => setLevel(entry().className, level)}
                  onRemove={() =>
                    draft.setValue('classes', removeClassEntry(entries(), entry().className))
                  }
                />
              )}
            </Index>
          </Show>
        </section>
      </div>

      {/* The tile is what asks, so the dialog runs controlled: it opens when a
          class is pending and clears the pending one however it closes. */}
      <ConfirmDialog
        open={pendingMulticlass() !== null}
        onOpenChange={(next) => !next && setPendingMulticlass(null)}
        title="Adicionar multiclasse?"
        description="Multiclasse é adquirida em níveis mais altos, pelo Poder de Multiclasse — não é padrão no nível 1. A sugestão de atributos continua sendo a da classe principal."
        confirmLabel="Adicionar mesmo assim"
        destructive={false}
        onConfirm={() => {
          const className = pendingMulticlass()
          if (className) addClass(className)
        }}
      />
    </section>
  )
}

function ChosenClass(props: {
  entry: ClassEntry
  isPrimary: boolean
  onLevel: (level: number) => void
  onRemove: () => void
}) {
  const levelId = () => `class-level-${props.entry.className}`
  return (
    <GrantBox
      title={props.isPrimary ? `${props.entry.className} · principal` : props.entry.className}
    >
      <div class="flex items-end gap-2">
        <div class="w-24">
          <label
            for={levelId()}
            class="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-muted-foreground"
          >
            Nível
          </label>
          <NumberInput
            id={levelId()}
            min={1}
            max={20}
            value={props.entry.level}
            onChange={props.onLevel}
            aria-label={`Nível de ${props.entry.className}`}
          />
        </div>
        <Show when={!props.isPrimary}>
          <Button
            type="button"
            variant="outline"
            size="sm"
            onClick={() => props.onRemove()}
            aria-label={`Tirar ${props.entry.className}`}
          >
            <X aria-hidden="true" class="size-3.5" />
            Tirar
          </Button>
        </Show>
      </div>
      <ClassGrantLines className={props.entry.className} level={props.entry.level} />
    </GrantBox>
  )
}
