// frontend-solid/src/shared/ui/framed-panel.tsx
import { type ComponentProps, splitProps } from 'solid-js'
import { cn } from '@/shared/lib/utils'

export type FramedPanelVariant = 'stone' | 'parchment'

export type FramedPanelProps = ComponentProps<'div'> & {
  variant?: FramedPanelVariant
}

/**
 * The default scene container: an iron border with a faint gold inset filete.
 * `stone` (dark, default) is the standard surface; `parchment` is a light aged
 * surface with dark ink for highlighted content (spell text, descriptions).
 * Meant to be used inside a `.scene-grimorio` scope.
 *
 * @example <FramedPanel variant="parchment" class="p-3">…</FramedPanel>
 */
export function FramedPanel(props: FramedPanelProps) {
  const [local, rest] = splitProps(props, ['class', 'variant', 'children'])
  const variant = () => local.variant ?? 'stone'
  return (
    <div
      data-slot="framed-panel"
      data-variant={variant()}
      class={cn(
        'grimorio-frame p-5',
        variant() === 'stone' ? 'grimorio-frame--stone text-foreground' : 'grimorio-parchment-bg',
        local.class,
      )}
      {...rest}
    >
      {local.children}
    </div>
  )
}

// frontend/src/shared/ui/framed-panel.tsx
import type * as React from 'react'
import { cn } from '@/shared/lib/utils'

/**
 * FramedPanel — the default scene container: an iron border with a faint gold
 * inset filete. `stone` (dark, default) is the standard surface; `parchment`
 * is a light aged surface with dark ink for highlighted content (spell text,
 * descriptions, cards). Meant to be used inside a `.scene-grimorio` scope.
 */
type FramedPanelVariant = 'stone' | 'parchment'

type FramedPanelProps = React.ComponentProps<'div'> & {
  variant?: FramedPanelVariant
}

function FramedPanel({
  className,
  variant = 'stone',
  children,
  ...props
}: FramedPanelProps) {
  return (
    <div
      data-slot="framed-panel"
      data-variant={variant}
      className={cn(
        'grimorio-frame p-5',
        variant === 'stone'
          ? 'grimorio-frame--stone text-foreground'
          : 'grimorio-parchment-bg',
        className,
      )}
      {...props}
    >
      {children}
    </div>
  )
}

export { FramedPanel }
export type { FramedPanelVariant }
