// frontend/src/routes/campaigns/session-tracker/initiative-card.tsx
import { useState } from 'react'
import { Plus, Swords, Trash2 } from 'lucide-react'
import { Badge } from '@/shared/ui/badge'
import { Button } from '@/shared/ui/button'
import { Card, CardContent, CardHeader } from '@/shared/ui/card'
import {
  ConnectionChip,
  type ConnectionStatus,
} from '@/shared/ui/connection-chip'
import { HpBar } from '@/shared/ui/hp-bar'
import { Input } from '@/shared/ui/input'
import { MpBar } from '@/shared/ui/mp-bar'
import { NumberInput } from '@/shared/ui/number-input'
import { SectionHeading } from '@/shared/ui/section-heading'
import { useSessionSocket, type InitiativeEntry } from '@/shared/realtime/realtime'

// Maps realtime hook state onto ConnectionChip's tri-state. The socket
// hook only reports `isConnected` + `error`; we infer 'reconnecting' as
// "not connected AND no fatal error yet" so a flicker between attempts
// shows the spinner instead of the offline glyph.
function deriveConnectionStatus(
  isConnected: boolean,
  error: string | null,
): ConnectionStatus {
  if (isConnected) return 'connected'
  if (error) return 'offline'
  return 'reconnecting'
}

export function InitiativeCard({
  campaignId,
  sessionId,
}: {
  campaignId: number
  sessionId: number
}) {
  const rt = useSessionSocket(campaignId, sessionId)
  const status = deriveConnectionStatus(rt.isConnected, rt.error)
  const [addLabel, setAddLabel] = useState('')
  const [addInit, setAddInit] = useState(10)
  const [addType, setAddType] = useState<'character' | 'npc'>('npc')

  const submitAdd = () => {
    const label = addLabel.trim()
    if (!label) return
    rt.addEntry({ label, initiative: addInit, type: addType })
    setAddLabel('')
    setAddInit(10)
  }

  return (
    <Card>
      <CardHeader className="flex flex-row items-start justify-between gap-3">
        <div className="space-y-2">
          <SectionHeading variant="kallyadranoch" as="h2">
            Iniciativa
          </SectionHeading>
          <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
            <ConnectionChip status={status} dirty={rt.hasPersistenceWarning} />
            <span className="font-hud tabular-nums">
              Rodada {rt.state.round}
            </span>
          </div>
        </div>
        <div className="flex gap-2">
          <Button size="sm" onClick={rt.nextTurn} disabled={!rt.isConnected}>
            Próximo turno
          </Button>
          <Button
            size="sm"
            variant="outline"
            onClick={rt.resetInitiative}
            disabled={!rt.isConnected}
          >
            Reset
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {rt.error && (
          <p className="text-sm text-destructive">
            Erro realtime: {rt.error}
          </p>
        )}

        {rt.state.initiative.length === 0 && (
          <p className="text-sm text-muted-foreground">
            Sem combatentes ainda. Adicione abaixo.
          </p>
        )}

        <div className="space-y-2">
          {rt.state.initiative.map((entry, idx) => (
            <InitiativeRow
              key={entry.id}
              entry={entry}
              onTurn={idx === rt.state.turnIndex}
              onDeltaHp={(delta) =>
                rt.deltaVitals(entry.id, { hpDelta: delta })
              }
              onRemove={() => rt.removeEntry(entry.id)}
            />
          ))}
        </div>

        <div className="mt-3 flex flex-wrap items-end gap-2 rounded-md border border-dashed p-3">
          <div className="min-w-[160px] flex-1">
            <label className="text-xs font-medium" htmlFor="add-label">
              Nome
            </label>
            <Input
              id="add-label"
              value={addLabel}
              onChange={(e) => setAddLabel(e.target.value)}
              placeholder="Goblin salteador…"
            />
          </div>
          <div className="w-24">
            <label className="text-xs font-medium" htmlFor="add-init">
              Iniciativa
            </label>
            <NumberInput
              id="add-init"
              min={-5}
              max={40}
              value={addInit}
              onChange={setAddInit}
            />
          </div>
          <div className="flex gap-1">
            <Button
              variant={addType === 'character' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setAddType('character')}
            >
              PC
            </Button>
            <Button
              variant={addType === 'npc' ? 'default' : 'outline'}
              size="sm"
              onClick={() => setAddType('npc')}
            >
              NPC
            </Button>
          </div>
          <Button
            onClick={submitAdd}
            disabled={!rt.isConnected || !addLabel.trim()}
          >
            <Plus className="mr-1 size-4" /> Adicionar
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}

function InitiativeRow({
  entry,
  onTurn,
  onDeltaHp,
  onRemove,
}: {
  entry: InitiativeEntry
  onTurn: boolean
  onDeltaHp: (delta: number) => void
  onRemove: () => void
}) {
  const hasHp = entry.hpMax !== undefined && entry.hpCurrent !== undefined
  const hasMp = entry.mpMax !== undefined
  return (
    <div
      data-on-turn={onTurn ? 'true' : 'false'}
      className={
        'flex flex-col gap-2 rounded-md border p-2.5 text-sm sm:flex-row sm:items-center sm:gap-3 ' +
        (onTurn
          ? 'border-[color:var(--primary)]/60 bg-[color-mix(in_oklch,var(--primary)_6%,transparent)]'
          : 'border-border/60')
      }
    >
      <div className="flex items-center gap-2">
        <Badge variant="outline" className="font-hud tabular-nums">
          {entry.initiative}
        </Badge>
        <div className="min-w-0 flex-1">
          <p className="flex flex-wrap items-center gap-1 truncate font-medium">
            <span className="truncate">{entry.label}</span>
            <Badge
              variant={entry.type === 'character' ? 'default' : 'secondary'}
              className="text-[10px] uppercase tracking-widest"
            >
              {entry.type === 'character' ? 'PC' : 'NPC'}
            </Badge>
            {onTurn && (
              <Badge className="gap-1 text-[10px] uppercase tracking-widest">
                <Swords className="size-3" /> Na vez
              </Badge>
            )}
          </p>
        </div>
      </div>

      {(hasHp || hasMp) && (
        <div className="flex-1 space-y-1.5 sm:min-w-[180px]">
          {hasHp && (
            <HpBar
              current={entry.hpCurrent!}
              max={entry.hpMax!}
              size="sm"
              label="PV"
            />
          )}
          {hasMp && (
            <MpBar
              current={entry.mpCurrent ?? 0}
              max={entry.mpMax!}
              size="sm"
              label="PM"
            />
          )}
        </div>
      )}

      <div className="flex items-center justify-end gap-1">
        {[-5, -1, 1, 5].map((delta) => (
          <Button
            key={delta}
            size="sm"
            variant="outline"
            onClick={() => onDeltaHp(delta)}
            className="h-9 min-w-9 font-hud tabular-nums sm:h-8 sm:min-w-8"
            aria-label={`Ajustar PV em ${delta}`}
          >
            {delta > 0 ? `+${delta}` : delta}
          </Button>
        ))}
        <Button
          size="sm"
          variant="ghost"
          onClick={onRemove}
          className="h-9 w-9 sm:h-8 sm:w-8"
          aria-label={`Remover ${entry.label}`}
        >
          <Trash2 className="size-4" />
        </Button>
      </div>
    </div>
  )
}

// frontend-solid/src/features/session-tracker/initiative-card.tsx
import { Plus, Swords, Trash2 } from 'lucide-solid'
import { For, Show, createEffect, createMemo, createSignal } from 'solid-js'
import type { InitiativeEntry, RestCondition, SessionRealtime } from '@/shared/realtime/realtime'
import { buffSpells } from '@/shared/lib/spell-cache'
import { cn } from '@/shared/lib/utils'
import { Button } from '@/shared/ui/button'
import { ConnectionChip } from '@/shared/ui/connection-chip'
import { Input } from '@/shared/ui/input'
import { NumberInput } from '@/shared/ui/number-input'
import { Select } from '@/shared/ui/select'
import { VitalBar } from '@/shared/ui/vital-bar'
import { InitiativeRollButton } from './initiative-roll'
import { type EntryPermissions, connectionStatus, entryPermissions } from './tracker-rules'

const REST_OPTIONS: { value: RestCondition; label: string }[] = [
  { value: 'ruim', label: 'Ruim (½ nível)' },
  { value: 'normal', label: 'Normal (nível)' },
  { value: 'confortavel', label: 'Confortável (2×)' },
  { value: 'luxuosa', label: 'Luxuosa (3×)' },
]

/** HP deltas the GM actually uses mid-combat — 1 and 5, both directions. */
const HP_DELTAS = [-5, -1, 1, 5]

/**
 * The initiative tracker: the primary surface of a live session. Everyone sees
 * the same order and the same bars; what changes by role is what you may TOUCH
 * (see `entryPermissions`).
 */
export function InitiativeCard(props: {
  rt: SessionRealtime
  isGm: boolean
  myCharacterIds: ReadonlySet<number>
}) {
  const [restCondition, setRestCondition] = createSignal<RestCondition>('normal')
  const myCharacterId = () => [...props.myCharacterIds][0]
  const status = () => connectionStatus(props.rt.isConnected(), props.rt.error())

  return (
    <section class="rounded-sm border border-grimorio-iron bg-[var(--grimorio-panel)]">
      <header class="flex flex-row items-start justify-between gap-3 border-b border-grimorio-iron p-3 sm:p-4">
        <div class="space-y-2">
          <h2 class="font-heading text-lg uppercase tracking-wide text-grimorio-gold">
            Iniciativa
          </h2>
          <div class="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
            <ConnectionChip status={status()} dirty={props.rt.hasPersistenceWarning()} />
            <span class="font-mono tabular-nums">Rodada {props.rt.state().round}</span>
          </div>
        </div>
        <Show when={props.isGm}>
          <div class="flex flex-wrap justify-end gap-2">
            <Button size="sm" disabled={!props.rt.isConnected()} onClick={props.rt.nextTurn}>
              Próximo turno
            </Button>
            <Button
              size="sm"
              variant="outline"
              disabled={!props.rt.isConnected()}
              onClick={props.rt.resetInitiative}
            >
              Reset
            </Button>
          </div>
        </Show>
      </header>

      <div class="space-y-3 p-3 sm:p-4">
        <Show when={props.rt.error()}>
          {(message) => <p class="text-sm text-destructive">Erro realtime: {message()}</p>}
        </Show>

        <Show when={!props.isGm && myCharacterId() !== undefined}>
          <InitiativeRollButton characterId={myCharacterId()} rt={props.rt} />
        </Show>

        <Show when={props.isGm}>
          <div class="flex flex-wrap items-center gap-2">
            <Button
              size="sm"
              variant="secondary"
              disabled={!props.rt.isConnected()}
              onClick={props.rt.populateParty}
            >
              Adicionar grupo
            </Button>
            <Button
              size="sm"
              variant="outline"
              disabled={!props.rt.isConnected()}
              onClick={() => props.rt.rest('scene')}
            >
              Descanso de cena
            </Button>
            <div class="flex items-center gap-1">
              <Select
                aria-label="Qualidade do descanso"
                size="sm"
                class="w-[150px]"
                options={REST_OPTIONS}
                value={REST_OPTIONS.find((o) => o.value === restCondition()) ?? null}
                onChange={(option) => setRestCondition(option?.value ?? 'normal')}
              />
              <Button
                size="sm"
                variant="outline"
                disabled={!props.rt.isConnected()}
                onClick={() => props.rt.rest('day', restCondition())}
              >
                Descanso de dia
              </Button>
            </div>
          </div>
        </Show>

        <Show when={props.rt.state().initiative.length === 0}>
          <p class="text-sm text-muted-foreground">
            {props.isGm
              ? 'Sem combatentes ainda. Adicione abaixo.'
              : 'Aguardando o mestre montar a iniciativa.'}
          </p>
        </Show>

        <div class="space-y-2">
          <For each={props.rt.state().initiative}>
            {(entry, index) => {
              const onTurn = () => index() === props.rt.state().turnIndex
              const can = () =>
                entryPermissions(entry, {
                  isGm: props.isGm,
                  myCharacterIds: props.myCharacterIds,
                })
              const isMine = () =>
                entry.characterId !== undefined && props.myCharacterIds.has(entry.characterId)
              return (
                <InitiativeRow
                  entry={entry}
                  onTurn={onTurn()}
                  focusOnTurn={onTurn() && isMine()}
                  can={can()}
                  onDeltaHp={(delta) => props.rt.deltaVitals(entry.id, { hpDelta: delta })}
                  onApplyEffect={(spellId) => props.rt.applyEffect(entry.id, spellId)}
                  onRemove={() => props.rt.removeEntry(entry.id)}
                />
              )
            }}
          </For>
        </div>

        <Show when={props.isGm}>
          <AddCombatantForm rt={props.rt} />
        </Show>
      </div>
    </section>
  )
}

function InitiativeRow(props: {
  entry: InitiativeEntry
  onTurn: boolean
  /** Scrolls into view when the viewer's OWN combatant takes its turn. */
  focusOnTurn: boolean
  can: EntryPermissions
  onDeltaHp: (delta: number) => void
  onApplyEffect: (spellId: string) => void
  onRemove: () => void
}) {
  let row: HTMLDivElement | undefined
  const hasHp = () => props.entry.hpMax !== undefined && props.entry.hpCurrent !== undefined
  const hasMp = () => props.entry.mpMax !== undefined

  createEffect(() => {
    if (props.focusOnTurn) row?.scrollIntoView({ block: 'center', behavior: 'smooth' })
  })

  return (
    <div
      ref={row}
      data-on-turn={props.onTurn ? 'true' : 'false'}
      class={cn(
        'flex flex-col gap-2 rounded-sm border p-2.5 text-sm sm:flex-row sm:items-center sm:gap-3',
        props.onTurn
          ? 'border-[color:var(--primary)]/60 bg-[color-mix(in_oklch,var(--primary)_6%,transparent)]'
          : 'border-border/60',
      )}
    >
      <div class="flex items-center gap-2">
        <span class="rounded-sm border border-border px-1.5 font-mono text-xs tabular-nums">
          {props.entry.initiative}
        </span>
        <p class="flex min-w-0 flex-wrap items-center gap-1 font-medium">
          <span class="truncate">{props.entry.label}</span>
          <span
            class={cn(
              'rounded-sm px-1 text-[10px] uppercase tracking-widest',
              props.entry.type === 'character'
                ? 'bg-primary text-primary-foreground'
                : 'bg-muted text-muted-foreground',
            )}
          >
            {props.entry.type === 'character' ? 'PC' : 'NPC'}
          </span>
          <Show when={props.onTurn}>
            <span class="inline-flex items-center gap-1 rounded-sm bg-primary px-1 text-[10px] uppercase tracking-widest text-primary-foreground">
              <Swords aria-hidden="true" class="size-3" /> Na vez
            </span>
          </Show>
        </p>
      </div>

      <Show when={hasHp() || hasMp()}>
        <div class="flex-1 space-y-1.5 sm:min-w-[180px]">
          <Show when={hasHp()}>
            <VitalBar
              kind="hp"
              label="PV"
              current={props.entry.hpCurrent ?? 0}
              max={props.entry.hpMax ?? 0}
            />
          </Show>
          <Show when={hasMp()}>
            <VitalBar
              kind="mp"
              label="PM"
              current={props.entry.mpCurrent ?? 0}
              max={props.entry.mpMax ?? 0}
            />
          </Show>
        </div>
      </Show>

      <div class="flex flex-wrap items-center justify-end gap-1">
        <Show when={props.can.applyEffect}>
          <ApplyEffectSelect onApply={props.onApplyEffect} />
        </Show>
        <Show when={props.can.editVitals}>
          <For each={HP_DELTAS}>
            {(delta) => (
              <Button
                size="sm"
                variant="outline"
                class="h-9 min-w-9 font-mono tabular-nums sm:h-8 sm:min-w-8"
                aria-label={`Ajustar PV de ${props.entry.label} em ${delta}`}
                onClick={() => props.onDeltaHp(delta)}
              >
                {delta > 0 ? `+${delta}` : delta}
              </Button>
            )}
          </For>
        </Show>
        <Show when={props.can.remove}>
          <Button
            size="sm"
            variant="ghost"
            class="h-9 w-9 sm:h-8 sm:w-8"
            aria-label={`Remover ${props.entry.label}`}
            onClick={() => props.onRemove()}
          >
            <Trash2 aria-hidden="true" class="size-4" />
          </Button>
        </Show>
      </div>
    </div>
  )
}

/**
 * The GM pushes a spell buff onto a combatant. Picking fires immediately and
 * the control resets, so the same buff can be re-applied (refreshing a scene
 * buff) — buffs are never automatic, this is the explicit GM-targets-a-player
 * affordance.
 */
function ApplyEffectSelect(props: { onApply: (spellId: string) => void }) {
  // From the primed cache: a module const would evaluate before priming.
  const options = createMemo(() => buffSpells().map((s) => ({ value: s.id, label: s.name })))
  return (
    <Select
      aria-label="Aplicar efeito"
      size="sm"
      class="h-9 w-9 justify-center p-0 sm:h-8 sm:w-8"
      options={options()}
      value={null}
      placeholder="✨"
      onChange={(option) => {
        if (option) props.onApply(option.value)
      }}
    />
  )
}

/** GM-only "add combatant" row: a name, an initiative in the playable range,
 *  and PC/NPC. Resets to a fresh NPC row after each add. */
function AddCombatantForm(props: { rt: SessionRealtime }) {
  const [label, setLabel] = createSignal('')
  const [initiative, setInitiative] = createSignal(10)
  const [type, setType] = createSignal<'character' | 'npc'>('npc')

  const trimmed = () => label().trim()
  const invalid = () => trimmed().length === 0 || trimmed().length > 60

  const submit = (event: SubmitEvent) => {
    event.preventDefault()
    if (invalid() || !props.rt.isConnected()) return
    props.rt.addEntry({ label: trimmed(), initiative: initiative(), type: type() })
    setLabel('')
    setInitiative(10)
    setType('npc')
  }

  return (
    <form
      class="mt-3 flex flex-wrap items-end gap-2 rounded-sm border border-dashed border-border p-3"
      onSubmit={submit}
      noValidate
    >
      <div class="min-w-[160px] flex-1 space-y-1">
        <label for="combatant-label" class="text-[10px] uppercase tracking-widest text-muted-foreground">
          Nome
        </label>
        <Input
          id="combatant-label"
          value={label()}
          onInput={(event) => setLabel(event.currentTarget.value)}
          placeholder="Goblin salteador…"
          maxLength={60}
        />
      </div>
      <div class="w-24 space-y-1">
        <label for="combatant-initiative" class="text-[10px] uppercase tracking-widest text-muted-foreground">
          Iniciativa
        </label>
        <NumberInput
          id="combatant-initiative"
          min={-5}
          max={40}
          value={initiative()}
          onChange={setInitiative}
        />
      </div>
      <div class="flex gap-1">
        <Button
          type="button"
          size="sm"
          variant={type() === 'character' ? 'default' : 'outline'}
          onClick={() => setType('character')}
        >
          PC
        </Button>
        <Button
          type="button"
          size="sm"
          variant={type() === 'npc' ? 'default' : 'outline'}
          onClick={() => setType('npc')}
        >
          NPC
        </Button>
      </div>
      <Button type="submit" disabled={!props.rt.isConnected() || invalid()}>
        <Plus aria-hidden="true" class="mr-1 size-4" /> Adicionar
      </Button>
    </form>
  )
}
