// frontend-solid/src/pages/home/home-page.tsx
import { useQueryClient, useQuery } from '@tanstack/solid-query'
import { useNavigate } from '@tanstack/solid-router'
import { PlayCircle, Scroll, Users2, Wand2 } from 'lucide-solid'
import { createSignal } from 'solid-js'
import { logout } from '@/entities/user/logout'
import { meQueryOptions } from '@/entities/user/queries'
import { createActiveSession } from '@/features/session-resume/active-session'
import { SceneShell } from '@/shared/layout/scene-shell'
import { createSceneNav } from '@/shared/lib/scene-nav'
import { createSfx } from '@/shared/lib/sfx'
import { useAuth } from '@/shared/stores/auth-context'
import { useUi } from '@/shared/stores/ui-context'
import { HubFooter } from './hub-footer'
import { type HubMenuItem, HubMenu } from './hub-menu'

/**
 * The Hub: the app's main menu, rendered as a full game scene. Three entries
 * into the main areas, "Continuar sessão" while a session is live, and the
 * player's identity footer.
 */
export function HomePage() {
  const navigate = useNavigate()
  const auth = useAuth()
  const ui = useUi()
  const queryClient = useQueryClient()
  const me = useQuery(() => meQueryOptions)
  const activeSession = createActiveSession()
  const sfx = createSfx(ui)
  const [signingOut, setSigningOut] = createSignal(false)

  const name = () => me.data?.name ?? me.data?.email ?? 'Aventureiro'

  // Play the select cue, then go — wraps each menu destination.
  const go = (select: () => void) => () => {
    sfx('select')
    select()
  }

  // Keyboard: the Hub is a single vertical menu region — ↑/↓ walk it, Enter
  // picks. It's the root scene, so Esc has nowhere to go back to (no-op).
  createSceneNav({
    root: () => document.querySelector<HTMLElement>('[data-slot="scene-shell"]'),
    onEscape: () => {},
    sfx,
  })

  const signOut = async () => {
    setSigningOut(true)
    try {
      await logout({ queryClient, auth })
      await navigate({ to: '/login' })
    } finally {
      setSigningOut(false)
    }
  }

  const items = (): HubMenuItem[] => {
    const base: HubMenuItem[] = [
      { label: 'Meus Heróis', icon: Users2, onSelect: go(() => navigate({ to: '/characters' })) },
      { label: 'Crônicas', icon: Scroll, onSelect: go(() => navigate({ to: '/campaigns' })) },
      { label: 'Ferramentas do Mestre', icon: Wand2, onSelect: go(() => navigate({ to: '/gm' })) },
    ]
    // Only surfaces while a session is live — a game's "Continue". Both GM and
    // players resume into the same match-mode screen.
    const live = activeSession()
    if (live) {
      base.push({
        label: 'Continuar sessão',
        icon: PlayCircle,
        hasNext: true,
        onSelect: go(() =>
          navigate({
            to: '/campaigns/$id/sessions/$sid',
            params: { id: String(live.campaignId), sid: String(live.sessionId) },
          }),
        ),
      })
    }
    return base
  }

  return (
    <SceneShell title="Tormenta 20" kicker="— Grimório de Arton —" onEnter={() => sfx('transition')}>
      <HubMenu class="mt-10" items={items()} onItemHover={() => sfx('hover')} />
      <HubFooter
        class="mt-auto"
        name={name()}
        onLogout={signOut}
        logoutPending={signingOut()}
        sfxEnabled={ui.sfx()}
        onToggleSfx={ui.toggleSfx}
      />
    </SceneShell>
  )
}

// frontend/src/pages/home/home-page.tsx
import { useQuery } from '@tanstack/react-query'
import { useNavigate } from '@tanstack/react-router'
import { Scroll, Users2, Wand2 } from 'lucide-react'
import { meQueryOptions } from '@/entities/user/queries'
import { useLogout } from '@/entities/user/use-logout'
import { SceneShell } from '@/shared/layout/scene-shell'
import { HubFooter } from './hub-footer'
import { HubMenu, type HubMenuItem } from './hub-menu'

/**
 * HomePage — the Hub: the app's main menu, rendered as a full game scene (a
 * bare route with no site nav — see the `inHub` bare-wiring in __root). Three
 * entries into the main areas plus the player's identity footer. "Continuar
 * sessão" (ALE-40) and the portrait quick-menu (ALE-39) slot in here next.
 */
export function HomePage() {
  const navigate = useNavigate()
  const me = useQuery(meQueryOptions)
  const logout = useLogout(() => navigate({ to: '/login' }))
  const name = me.data?.name ?? me.data?.email ?? 'Aventureiro'

  const items: HubMenuItem[] = [
    {
      label: 'Meus Heróis',
      icon: Users2,
      onSelect: () => navigate({ to: '/characters' }),
    },
    {
      label: 'Crônicas',
      icon: Scroll,
      onSelect: () => navigate({ to: '/campaigns' }),
    },
    {
      label: 'Ferramentas do Mestre',
      icon: Wand2,
      onSelect: () => navigate({ to: '/gm' }),
    },
  ]

  return (
    <SceneShell title="Tormenta 20" kicker="— Grimório de Arton —">
      <HubMenu className="mt-10" items={items} />
      <HubFooter
        className="mt-auto"
        name={name}
        onLogout={() => logout.mutate()}
        logoutPending={logout.isPending}
      />
    </SceneShell>
  )
}
