// frontend-solid/src/features/campaign-manage/members-card.tsx
import { useQuery, useQueryClient } from '@tanstack/solid-query'
import { Link } from '@tanstack/solid-router'
import { Crown, Trash2, Users } from 'lucide-solid'
import { For, Show, createSignal } from 'solid-js'
import { campaignMembersQueryOptions } from '@/entities/campaign/queries'
import { classLevelLine } from '@/entities/character/class-line'
import { type CampaignMember, api } from '@/shared/api/api'
import { hueFromName } from '@/shared/lib/hue-from-name'
import { Button } from '@/shared/ui/button'
import { CharacterPortrait } from '@/shared/ui/character-portrait'
import { SkeletonRows } from '@/shared/ui/skeleton'
import { InviteButton } from './invite-button'
import { TomeSection } from './tome-section'

/** GM first (the crest leads the muster), then the rest in arrival order. */
export function sortRoster(members: readonly CampaignMember[]): CampaignMember[] {
  return [...members].sort((a, b) => (a.role === b.role ? 0 : a.role === 'gm' ? -1 : 1))
}

/** A member's display name — the character's, or a placeholder by id. */
export function memberName(member: CampaignMember): string {
  return member.character?.name ?? `Personagem ${member.characterId}`
}

/**
 * Membros section as a PARTY ROSTER — every hero as a portrait plate (the GM
 * crowned), laid out as a grid that grows columns with the tome page. Players
 * are never added here; the GM shares an invite link and each player joins
 * with a character of their own.
 */
export function MembersCard(props: { campaignId: number; isGm: boolean }) {
  const members = useQuery(() => campaignMembersQueryOptions(props.campaignId))
  const roster = () => sortRoster(members.data ?? [])
  const queryClient = useQueryClient()

  /** Drops a member and clears the character's now-stale "Campanhas" list. */
  const remove = async (member: CampaignMember) => {
    await api.members.remove(props.campaignId, member.id)
    await queryClient.invalidateQueries({
      queryKey: campaignMembersQueryOptions(props.campaignId).queryKey,
    })
    await queryClient.invalidateQueries({
      queryKey: ['characters', member.characterId, 'campaigns'],
    })
  }

  return (
    <TomeSection
      eyebrow="A Mesa"
      title="Heróis"
      action={<Show when={props.isGm}>{<InviteButton campaignId={props.campaignId} />}</Show>}
    >
      <Show when={props.isGm}>
        <p class="text-sm text-muted-foreground">
          Jogadores entram pelo link de convite com um personagem próprio.
        </p>
      </Show>
      <Show when={members.isLoading}>
        <SkeletonRows count={2} />
      </Show>
      <Show when={!members.isLoading && roster().length === 0}>
        <EmptyMuster />
      </Show>
      <Show when={roster().length > 0}>
        <div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
          <For each={roster()}>
            {(member) => (
              <MemberPlate
                member={member}
                canRemove={props.isGm}
                onRemove={() => remove(member)}
              />
            )}
          </For>
        </div>
      </Show>
    </TomeSection>
  )
}

/** No members yet — an empty muster awaiting the first hero. */
function EmptyMuster() {
  return (
    <div class="flex flex-col items-center gap-2 rounded-sm border border-dashed border-grimorio-iron px-4 py-10 text-center">
      <Users aria-hidden="true" class="size-6 text-muted-foreground" />
      <p class="text-sm text-muted-foreground">Nenhum personagem inscrito ainda.</p>
    </div>
  )
}

export type MemberPlateProps = {
  member: CampaignMember
  /** Only the GM may drop someone from the muster. */
  canRemove: boolean
  onRemove: () => Promise<void>
}

export function MemberPlate(props: MemberPlateProps) {
  const name = () => memberName(props.member)
  const character = () => props.member.character
  const isGm = () => props.member.role === 'gm'

  return (
    <div class="group relative flex items-center gap-3 rounded-sm border border-grimorio-iron bg-[var(--grimorio-panel)] p-3">
      <CharacterPortrait name={name()} size="sm" hue={hueFromName(name())} />
      <div class="min-w-0 flex-1">
        <p class="flex items-center gap-1.5 truncate font-medium text-foreground">
          {name()}
          <Show when={isGm()}>
            <Crown aria-hidden="true" class="size-3.5 shrink-0 text-grimorio-gold" />
          </Show>
        </p>
        <p class="truncate text-xs text-muted-foreground">
          {classLevelLine(character()?.classes ?? []) || `Nv ${character()?.level ?? 1}`}
        </p>
      </div>
      <Show when={character()}>
        {(char) => (
          <Link
            to="/characters/$id"
            params={{ id: String(char().id) }}
            class="shrink-0 text-xs text-grimorio-gold hover:underline"
          >
            Ficha
          </Link>
        )}
      </Show>
      <Show when={props.canRemove}>
        <RemoveMemberButton name={name()} onRemove={props.onRemove} />
      </Show>
    </div>
  )
}

/**
 * Drops a hero from the muster. Hidden until hover/focus so the roster reads as
 * a roster, and `data-nav-skip` keeps it out of the arrow-key cursor — nobody
 * should land on "remove" by walking the grid. On a touch screen there IS no
 * hover, so it stays visible there or the GM could never remove anyone.
 */
function RemoveMemberButton(props: { name: string; onRemove: () => Promise<void> }) {
  const [pending, setPending] = createSignal(false)

  const remove = async () => {
    setPending(true)
    try {
      await props.onRemove()
    } finally {
      setPending(false)
    }
  }

  return (
    <Button
      variant="ghost"
      size="icon-sm"
      data-nav-skip
      class="absolute top-1.5 right-1.5 opacity-0 transition-opacity pointer-coarse:opacity-100 focus-visible:opacity-100 group-hover:opacity-100"
      onClick={remove}
      disabled={pending()}
      aria-label={`Remover ${props.name}`}
    >
      <Trash2 aria-hidden="true" class="size-4" />
    </Button>
  )
}

// frontend/src/routes/campaigns/campaign-detail/members-card.tsx
import { Link } from '@tanstack/react-router'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { Trash2, UserPlus } from 'lucide-react'
import { Badge } from '@/shared/ui/badge'
import { Button } from '@/shared/ui/button'
import { Card, CardContent, CardHeader } from '@/shared/ui/card'
import { Combobox } from '@/shared/ui/combobox'
import { SectionHeading } from '@/shared/ui/section-heading'
import { SkeletonRows } from '@/shared/ui/skeleton'
import { ApiError, api } from '@/shared/api/api'
import type {
  CampaignMember,
  CampaignMemberRole,
  Character,
} from '@/shared/api/api'
import {
  campaignMembersQueryOptions,
  charactersQueryOptions,
} from '@/shared/lib/queries'

export function MembersCard({ campaignId }: { campaignId: number }) {
  const members = useQuery(campaignMembersQueryOptions(campaignId))

  return (
    <Card>
      <CardHeader>
        <SectionHeading as="h2">Membros</SectionHeading>
      </CardHeader>
      <CardContent className="space-y-4">
        <AddMemberForm campaignId={campaignId} />
        {members.isLoading && <SkeletonRows count={2} />}
        {members.data?.length === 0 && (
          <p className="text-sm text-muted-foreground">
            Nenhum personagem inscrito ainda.
          </p>
        )}
        <div className="space-y-2">
          {members.data?.map((m) => (
            <MemberRow key={m.id} member={m} campaignId={campaignId} />
          ))}
        </div>
      </CardContent>
    </Card>
  )
}

function AddMemberForm({ campaignId }: { campaignId: number }) {
  const qc = useQueryClient()
  const characters = useQuery(charactersQueryOptions)
  const members = useQuery(campaignMembersQueryOptions(campaignId))
  const [characterId, setCharacterId] = useState<string>('')
  const [role, setRole] = useState<CampaignMemberRole>('player')
  const [error, setError] = useState<string | null>(null)

  const mutation = useMutation({
    mutationFn: () =>
      api.members.add(campaignId, {
        characterId: Number(characterId),
        role,
      }),
    onSuccess: () => {
      qc.invalidateQueries({
        queryKey: campaignMembersQueryOptions(campaignId).queryKey,
      })
      /* The character just joined — its "Campanhas" tab is stale. */
      qc.invalidateQueries({
        queryKey: ['characters', Number(characterId), 'campaigns'],
      })
      setCharacterId('')
      setError(null)
    },
    onError: (e) => {
      setError(e instanceof ApiError ? e.message : 'Erro ao adicionar')
    },
  })

  const alreadyIn = new Set(members.data?.map((m) => m.characterId) ?? [])
  const available = (characters.data ?? []).filter(
    (c) => !alreadyIn.has(c.id),
  )

  return (
    <div className="rounded-md border border-dashed p-3">
      <p className="mb-2 text-sm font-medium">Adicionar personagem</p>
      <div className="flex flex-wrap items-end gap-2">
        <div className="min-w-[220px] flex-1">
          <Combobox
            options={available.map((c: Character) => ({
              value: String(c.id),
              label: `${c.name} (Lv ${c.level})`,
            }))}
            value={characterId}
            onChange={setCharacterId}
            placeholder="Selecionar personagem"
            searchPlaceholder="Buscar…"
            emptyMessage="Nenhum personagem disponível."
          />
        </div>
        <div className="w-32">
          <Combobox
            options={[
              { value: 'player', label: 'Jogador' },
              { value: 'gm', label: 'GM' },
            ]}
            value={role}
            onChange={(v) => setRole(v as CampaignMemberRole)}
            placeholder="Papel"
            searchPlaceholder=""
            emptyMessage=""
          />
        </div>
        <Button
          disabled={!characterId || mutation.isPending}
          onClick={() => mutation.mutate()}
        >
          <UserPlus className="mr-1 size-4" />
          {mutation.isPending ? 'Adicionando…' : 'Adicionar'}
        </Button>
      </div>
      {error && <p className="mt-2 text-sm text-destructive">{error}</p>}
    </div>
  )
}

function MemberRow({
  member,
  campaignId,
}: {
  member: CampaignMember
  campaignId: number
}) {
  const qc = useQueryClient()
  const mutation = useMutation({
    mutationFn: () => api.members.remove(campaignId, member.id),
    onSuccess: () => {
      qc.invalidateQueries({
        queryKey: campaignMembersQueryOptions(campaignId).queryKey,
      })
      /* The character no longer belongs to this campaign — its
       * "Campanhas" tab still lists the stale row. */
      qc.invalidateQueries({
        queryKey: ['characters', member.characterId, 'campaigns'],
      })
    },
  })

  const char = member.character
  const classes =
    char?.classes.map((c) => `${c.className} ${c.level}`).join(' / ') ?? '—'

  return (
    <div className="flex items-center justify-between rounded-md border p-2 text-sm transition hover:border-[color:var(--primary)]/50">
      <Link
        to="/characters/$id"
        params={{ id: String(member.characterId) }}
        className="flex-1"
      >
        <p className="flex flex-wrap items-center gap-1 font-medium">
          <span>{char?.name ?? `Character ${member.characterId}`}</span>
          <Badge variant="secondary">Lv {char?.level ?? '?'}</Badge>
          <Badge variant={member.role === 'gm' ? 'default' : 'outline'}>
            {member.role === 'gm' ? 'GM' : 'Jogador'}
          </Badge>
        </p>
        <p className="text-xs text-muted-foreground">{classes}</p>
      </Link>
      <Button
        variant="ghost"
        size="sm"
        onClick={() => mutation.mutate()}
        disabled={mutation.isPending}
        aria-label={`Remover ${char?.name ?? 'personagem'}`}
      >
        <Trash2 className="size-4" />
      </Button>
    </div>
  )
}
