// frontend/src/features/character-sheet/pendencias-callout.tsx
import { AlertTriangle, Check } from 'lucide-react'
import type { Pendencia } from './pendencias'

/**
 * The "what's left to decide" banner pinned above the source sub-tabs. Each
 * bullet jumps to the tab + card that owns the choice. When nothing is
 * pending it shows a compact success row (kept mounted to avoid layout jump).
 */
export function PendenciasCallout({
  pendencias,
  onJump,
}: {
  pendencias: Pendencia[]
  onJump: (pendencia: Pendencia) => void
}) {
  if (pendencias.length === 0) {
    return (
      <div className="flex items-center gap-2 rounded-lg border border-emerald-600/30 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-700 dark:text-emerald-300">
        <Check className="size-4 shrink-0" />
        Todas as escolhas feitas.
      </div>
    )
  }
  return (
    <div className="rounded-lg border border-amber-600/40 bg-amber-500/10 px-3 py-2">
      <p className="flex items-center gap-1.5 text-xs font-semibold text-amber-700 dark:text-amber-300">
        <AlertTriangle className="size-3.5 shrink-0" /> Faltam escolhas
      </p>
      <ul className="mt-1 max-h-32 space-y-0.5 overflow-y-auto">
        {pendencias.map((p) => (
          <li key={`${p.cardId}:${p.label}`}>
            <button
              type="button"
              onClick={() => onJump(p)}
              className="text-left text-xs text-amber-800 underline-offset-2 hover:underline dark:text-amber-200"
            >
              • {p.label}
            </button>
          </li>
        ))}
      </ul>
    </div>
  )
}

// frontend-solid/src/features/character-sheet/pendencias-callout.tsx
import { AlertTriangle, Check } from 'lucide-solid'
import { For, Show } from 'solid-js'
import type { Pendencia } from './pendencias'

/**
 * The "what's left to decide" banner pinned above the source sub-tabs. Each
 * bullet jumps to the tab + card that owns the choice; with nothing pending it
 * shows a compact success row, kept mounted so the list below never jumps.
 */
export function PendenciasCallout(props: {
  pendencias: Pendencia[]
  onJump: (pendencia: Pendencia) => void
}) {
  return (
    <Show
      when={props.pendencias.length > 0}
      fallback={
        <div class="flex items-center gap-2 rounded-sm border border-emerald-600/30 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-300">
          <Check aria-hidden="true" class="size-4 shrink-0" />
          Todas as escolhas feitas.
        </div>
      }
    >
      <div class="rounded-sm border border-amber-600/40 bg-amber-500/10 px-3 py-2">
        <p class="flex items-center gap-1.5 text-xs font-semibold text-amber-300">
          <AlertTriangle aria-hidden="true" class="size-3.5 shrink-0" /> Faltam escolhas
        </p>
        <ul class="mt-1 max-h-32 space-y-0.5 overflow-y-auto">
          <For each={props.pendencias}>
            {(pendencia) => (
              <li>
                <button
                  type="button"
                  onClick={() => props.onJump(pendencia)}
                  class="text-left text-xs text-amber-200 underline-offset-2 hover:underline"
                >
                  • {pendencia.label}
                </button>
              </li>
            )}
          </For>
        </ul>
      </div>
    </Show>
  )
}
