// frontend/src/features/character-sheet/spell-row.tsx
import { useState } from 'react'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { BookPlus, BookX, Check, Sparkles } from 'lucide-react'
import {
  CLASS_SPELLCASTING_ATTRIBUTE,
  SPELL_BASE_PM_COST,
  firstErrorMessage,
  highestCircleAtLevel,
  spellSaveDc,
  validateLearnSpell,
  validateSpellLearned,
  type AttributeKey,
  type CatalogSpell,
  type ItemEffects,
  type SpellCircle,
  type SpellcasterClass,
} from '@tormenta20/t20-data'
import { hasSpell } from '@/shared/lib/spell-cache'
import { Badge } from '@/shared/ui/badge'
import { Button } from '@/shared/ui/button'
import type { Character, CharacterSpell } from '@/shared/api/api'
import { api } from '@/shared/api/api'
import { invalidateCharacterDependents } from '@/entities/character/character-cache'
import { attributeTotal } from '@/entities/character/derived'
import { characterQueryOptions } from '@/entities/character/queries'
import { accentStrong, dimText, hoverRow } from '@/shared/lib/sheet-theme'
import { cn } from '@/shared/lib/utils'
import { CastSpellDialog } from './cast-spell-dialog'
import { CIRCLE_LABEL, SCHOOL_LABEL } from './spell-labels'

/**
 * One catalog row. Header collapses to name + círculo + escola + PM +
 * CD + status badge, plus an always-visible Conjurar trigger for
 * learned spells (icon-only below `sm`) so casting never requires
 * expanding the row; expands to full stats + augment list + action
 * cluster (Aprender / Preparar / Esquecer). At phone width the header
 * chip cluster wraps under the name instead of crushing it. Mutations
 * invalidate the character query so persisted spells reflect
 * immediately in the "Aprendidas" filter.
 */
export type GrantedSpellMeta = {
  /** Power that teaches the spell — shown as a badge, hides spellbook
   *  management (you can't unlearn a power-granted spell). */
  sourcePower: string
  /** Key attribute the granting power casts with (Totem: Sab, p42). */
  keyAttribute: AttributeKey
}

export function SpellRow({
  spell,
  character,
  casterClasses,
  learned,
  effects,
  granted,
}: {
  spell: CatalogSpell
  character: Character
  casterClasses: readonly SpellcasterClass[]
  learned: CharacterSpell | null
  effects: ItemEffects
  granted?: GrantedSpellMeta
}) {
  const [open, setOpen] = useState(false)
  const qc = useQueryClient()
  const queryKey = characterQueryOptions(character.id).queryKey

  const applicableClasses = casterClasses.filter((c) =>
    spell.classes.includes(c),
  )
  // Power-granted spells cast with the power's own attribute and are always
  // "learned"; the row synthesizes the CharacterSpell it never persists.
  const effectiveLearned =
    granted && !learned
      ? { id: -1, catalogSpellId: spell.id, prepared: true, learnedAt: '' }
      : learned
  const bestCd = granted
    ? spellSaveDc(
        character.level,
        attributeTotal(character, granted.keyAttribute, effects),
      )
    : computeBestCd(character, applicableClasses, effects)
  const cast = highestCastableCircle(character, applicableClasses)
  const canCast = granted ? true : spell.circle <= cast

  // Optimistic spellbook edits: the shared t20-data rules pre-validate each
  // change so we can predict the server's answer and patch the cache before the
  // round-trip; `onError` rolls back if the prediction was wrong.
  const patchSpells = (next: (spells: CharacterSpell[]) => CharacterSpell[]) => {
    const prev = qc.getQueryData<Character>(queryKey)
    qc.setQueryData<Character>(queryKey, (c) =>
      c ? { ...c, spells: next(c.spells) } : c,
    )
    return prev
  }
  const rollback = (prev: Character | undefined) => {
    if (prev) qc.setQueryData(queryKey, prev)
  }
  const knownIds = character.spells.map((s) => s.catalogSpellId)

  const learn = useMutation({
    mutationFn: () => api.characters.learnSpell(character.id, spell.id),
    onMutate: async () => {
      await qc.cancelQueries({ queryKey })
      // Temp negative id until the server assigns the real row.
      return {
        prev: patchSpells((spells) => [
          ...spells,
          {
            id: -Date.now(),
            catalogSpellId: spell.id,
            prepared: false,
            learnedAt: new Date().toISOString(),
          },
        ]),
      }
    },
    onError: (_e, _v, ctx) => rollback(ctx?.prev),
    onSettled: () => {
      qc.invalidateQueries({ queryKey })
      invalidateCharacterDependents(qc, character.id)
    },
  })
  const unlearn = useMutation({
    mutationFn: () => api.characters.unlearnSpell(character.id, spell.id),
    onMutate: async () => {
      await qc.cancelQueries({ queryKey })
      return {
        prev: patchSpells((spells) =>
          spells.filter((s) => s.catalogSpellId !== spell.id),
        ),
      }
    },
    onError: (_e, _v, ctx) => rollback(ctx?.prev),
    onSettled: () => {
      qc.invalidateQueries({ queryKey })
      invalidateCharacterDependents(qc, character.id)
    },
  })
  const setPrepared = useMutation({
    mutationFn: (prepared: boolean) =>
      api.characters.setSpellPrepared(character.id, spell.id, prepared),
    onMutate: async (prepared) => {
      await qc.cancelQueries({ queryKey })
      return {
        prev: patchSpells((spells) =>
          spells.map((s) =>
            s.catalogSpellId === spell.id ? { ...s, prepared } : s,
          ),
        ),
      }
    },
    onError: (_e, _v, ctx) => rollback(ctx?.prev),
    onSettled: () => qc.invalidateQueries({ queryKey }),
  })

  // Guard before mutating so an optimistic patch is only applied when the
  // shared domain rule says the server will accept it.
  const doLearn = () => {
    const err = firstErrorMessage(
      validateLearnSpell(knownIds, spell.id, hasSpell(spell.id)),
    )
    if (err) return toast.error(err)
    learn.mutate()
  }
  const doSetPrepared = (prepared: boolean) => {
    const err = firstErrorMessage(validateSpellLearned(knownIds, spell.id))
    if (err) return toast.error(err)
    setPrepared.mutate(prepared)
  }

  return (
    <div
      className={cn(
        'rounded-md border border-transparent px-2 py-1',
        hoverRow,
        open && 'border-border ',
      )}
    >
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={() => setOpen((o) => !o)}
          className="flex min-w-0 flex-1 flex-wrap items-center gap-x-2 gap-y-1 text-left"
          aria-expanded={open}
        >
          <Badge
            variant="outline"
            className={cn('font-mono text-[10px]', !canCast && dimText)}
          >
            {CIRCLE_LABEL[spell.circle]}
          </Badge>
          {/* basis-32 + flex-wrap: the name claims ~8rem before the chip
              cluster may share the line, so at 390px the chips wrap below
              instead of crushing the name to 1-4 chars. */}
          <span className="min-w-0 flex-1 basis-32 truncate text-sm font-medium">
            {spell.name}
          </span>
          <span className="ml-auto flex shrink-0 items-center gap-2">
            <span
              className={cn(
                'hidden text-[10px] uppercase tracking-widest sm:inline',
                dimText,
              )}
            >
              {SCHOOL_LABEL[spell.school]}
            </span>
            <span className={cn('font-mono text-xs', accentStrong)}>
              {SPELL_BASE_PM_COST[spell.circle]} PM
            </span>
            {bestCd !== null && (
              <span className="font-mono text-xs text-violet-700 dark:text-violet-300">
                CD {bestCd}
              </span>
            )}
            {granted ? (
              <Badge
                variant="outline"
                className="text-[10px] uppercase tracking-widest"
              >
                {granted.sourcePower}
              </Badge>
            ) : (
              learned && (
                <Badge
                  variant={learned.prepared ? 'default' : 'secondary'}
                  className="text-[10px] uppercase tracking-widest"
                >
                  {learned.prepared ? 'Preparada' : 'Aprendida'}
                </Badge>
              )
            )}
          </span>
        </button>
        {effectiveLearned && (
          <CastSpellDialog
            spell={spell}
            character={character}
            disabled={!canCast}
            compact
          />
        )}
      </div>
      {open && (
        <div className="mt-2 space-y-2 border-t border-border pt-2 text-xs ">
          <div className="grid gap-1 sm:grid-cols-2">
            <Stat label="Execução" value={spell.execution} />
            <Stat label="Alcance" value={spell.range} />
            <Stat
              label="Duração"
              value={
                spell.duration === 'definida' && spell.durationNote
                  ? spell.durationNote
                  : spell.duration
              }
            />
            <Stat label="Resistência" value={spell.resistance ?? '—'} />
            <Stat label="Teste" value={spell.saveType} />
            <Stat label="Livro" value={`p${spell.bookPage}`} />
          </div>
          <p className="whitespace-pre-line text-foreground ">
            {spell.baseEffect}
          </p>
          {spell.augments.length > 0 && (
            <div className="space-y-1">
              <p
                className={cn(
                  'text-[10px] uppercase tracking-widest',
                  dimText,
                )}
              >
                Aprimoramentos
              </p>
              <ul className="space-y-1">
                {spell.augments.map((a, i) => (
                  <li
                    key={i}
                    className="flex items-start gap-2 rounded border border-border px-2 py-1 "
                  >
                    <Badge
                      variant="outline"
                      className="font-mono text-[10px]"
                    >
                      +{a.pmCost} PM
                    </Badge>
                    <span
                      className={cn(
                        'text-[10px] uppercase tracking-widest',
                        a.kind === 'muda'
                          ? 'text-violet-700 dark:text-violet-300'
                          : 'text-emerald-700 dark:text-emerald-300',
                      )}
                    >
                      {a.kind}
                    </span>
                    <span className="flex-1 text-foreground ">
                      {a.description}
                      {a.classOnly && (
                        <span className={cn('ml-1 italic', dimText)}>
                          (apenas {a.classOnly})
                        </span>
                      )}
                      {a.requiresCircle !== undefined && (
                        <span className={cn('ml-1 italic', dimText)}>
                          (requer {CIRCLE_LABEL[a.requiresCircle]})
                        </span>
                      )}
                    </span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {!canCast && applicableClasses.length > 0 && (
            <p className="flex items-center gap-1 text-[11px] text-foreground ">
              <Sparkles className="size-3" />
              Círculo acima do máximo conjurável no nível atual.
            </p>
          )}
          {granted ? null : (
          <div className="flex flex-wrap items-center gap-2 border-t border-border pt-2 ">
            {/* Conjurar lives in the always-visible header (same learned +
                canCast gating) — the expanded cluster keeps the spellbook
                management actions only. */}
            {learned ? (
              <>
                <Button
                  type="button"
                  size="sm"
                  variant={learned.prepared ? 'default' : 'outline'}
                  className="h-7 gap-1 text-xs"
                  disabled={setPrepared.isPending}
                  onClick={() => doSetPrepared(!learned.prepared)}
                >
                  <Check className="size-3.5" />
                  {learned.prepared ? 'Despreparar' : 'Preparar'}
                </Button>
                <Button
                  type="button"
                  size="sm"
                  variant="ghost"
                  className="h-7 gap-1 text-xs text-red-700 hover:bg-red-100 dark:text-red-400 dark:hover:bg-red-950/40"
                  disabled={unlearn.isPending}
                  onClick={() => unlearn.mutate()}
                >
                  <BookX className="size-3.5" />
                  Esquecer
                </Button>
              </>
            ) : (
              <Button
                type="button"
                size="sm"
                variant="outline"
                className="h-7 gap-1 text-xs"
                disabled={learn.isPending}
                onClick={doLearn}
              >
                <BookPlus className="size-3.5" />
                Aprender
              </Button>
            )}
          </div>
          )}
        </div>
      )}
    </div>
  )
}

function Stat({ label, value }: { label: string; value: string | number }) {
  return (
    <div className="flex items-baseline gap-1">
      <span
        className={cn('text-[10px] uppercase tracking-widest', dimText)}
      >
        {label}
      </span>
      <span className="text-foreground ">{value}</span>
    </div>
  )
}

/**
 * Best CD among the classes able to cast THIS spell. Uses the FINAL key
 * attribute (attributeTotal — race/item bonuses in), matching the sheet's
 * "CD Magia" box; the raw stored attribute understated the row CD
 * (Necromante Osteon: row showed 21, sheet 22). PDF p171.
 */
function computeBestCd(
  character: Character,
  applicableClasses: readonly SpellcasterClass[],
  effects: ItemEffects,
): number | null {
  if (applicableClasses.length === 0) return null
  let best = -Infinity
  for (const c of applicableClasses) {
    const attr = CLASS_SPELLCASTING_ATTRIBUTE[c]
    if (!attr) continue
    const dc = spellSaveDc(
      character.level,
      attributeTotal(character, attr, effects),
    )
    if (dc > best) best = dc
  }
  return best === -Infinity ? null : best
}

function highestCastableCircle(
  character: Character,
  applicableClasses: readonly SpellcasterClass[],
): SpellCircle {
  let best: SpellCircle = 0
  for (const c of applicableClasses) {
    const classEntry = character.classes.find((cc) => cc.className === c)
    if (!classEntry) continue
    const circle = highestCircleAtLevel(c, classEntry.level)
    if (circle > best) best = circle
  }
  return best
}

// frontend-solid/src/features/character-sheet/spell-row.tsx
import { useQueryClient } from '@tanstack/solid-query'
import {
  type AttributeKey,
  type CatalogSpell,
  SPELL_BASE_PM_COST,
  type SpellcasterClass,
  firstErrorMessage,
  validateLearnSpell,
  validateSpellLearned,
} from '@tormenta20/t20-data'
import { BookPlus, BookX, Check, Sparkles } from 'lucide-solid'
import { For, Show, createMemo, createSignal } from 'solid-js'
import { bestSpellCd, castableClassesFor, highestCastableCircle } from '@/entities/character/spell-rules'
import type { Character, CharacterSpell } from '@/shared/api/api'
import { hasSpell } from '@/shared/lib/spell-cache'
import { Button } from '@/shared/ui/button'
import { toast } from '@/shared/ui/sonner'
import { cn } from '@/shared/lib/utils'
import { CastSpellDialog } from './cast-spell-dialog'
import { CIRCLE_LABEL, SCHOOL_LABEL } from './spell-labels'
import { spellActions } from './spell-mutations'

/** A spell taught by a power (Totem Espiritual, p42). */
export type GrantedSpellMeta = {
  /** The power that teaches it — shown as a badge; a granted spell cannot be
   *  unlearned, so the spellbook actions hide. */
  sourcePower: string
  /** Key attribute the granting power casts with (Totem: Sab, p42). */
  keyAttribute: AttributeKey
}

/**
 * One catalog row. Collapsed it shows name + círculo + escola + PM + CD +
 * status, plus an always-visible Conjurar for learned spells (icon-only below
 * `sm`) — casting must never require expanding the row. Expanded it adds the
 * full stats, the augment list and the spellbook actions.
 */
export function SpellRow(props: {
  spell: CatalogSpell
  character: Character
  learned: CharacterSpell | null
  /** Spell save CD per casting attribute, from the computed sheet (p171). */
  spellCdByAttribute: Record<AttributeKey, number>
  granted?: GrantedSpellMeta
}) {
  const queryClient = useQueryClient()
  const [open, setOpen] = createSignal(false)
  const [pending, setPending] = createSignal(false)

  const applicableClasses = createMemo<SpellcasterClass[]>(() =>
    castableClassesFor(props.character, props.spell.classes),
  )
  const bestCd = () =>
    props.granted
      ? props.spellCdByAttribute[props.granted.keyAttribute]
      : bestSpellCd(applicableClasses(), props.spellCdByAttribute)
  // A granted spell is castable at its own circle even for a non-caster.
  const canCast = () =>
    Boolean(props.granted) ||
    props.spell.circle <= highestCastableCircle(props.character, applicableClasses())
  const castable = () => Boolean(props.granted) || Boolean(props.learned)

  const knownIds = () => props.character.spells.map((spell) => spell.catalogSpellId)

  /** Guard with the SHARED rule before mutating, so an optimistic patch is only
   *  applied when the server is going to agree. */
  const run = async (refusal: string | null | undefined, write: () => Promise<void>) => {
    if (refusal) {
      toast.error(refusal)
      return
    }
    setPending(true)
    try {
      await write()
    } catch {
      // spellActions already rolled back and told the player.
    } finally {
      setPending(false)
    }
  }

  const actions = () => spellActions(queryClient, props.character.id)

  const learn = () =>
    run(
      firstErrorMessage(
        validateLearnSpell(knownIds(), props.spell.id, hasSpell(props.spell.id)),
      ),
      () => actions().learn(props.spell.id),
    )
  const setPrepared = (prepared: boolean) =>
    run(firstErrorMessage(validateSpellLearned(knownIds(), props.spell.id)), () =>
      actions().setPrepared(props.spell.id, prepared),
    )
  const unlearn = () => run(undefined, () => actions().unlearn(props.spell.id))

  return (
    <div
      class={cn(
        'rounded-md border border-transparent px-2 py-1 hover:bg-accent/40',
        open() && 'border-border',
      )}
    >
      <div class="flex items-center gap-2">
        <button
          type="button"
          onClick={() => setOpen(!open())}
          aria-expanded={open()}
          class="flex min-w-0 flex-1 flex-wrap items-center gap-x-2 gap-y-1 text-left"
        >
          <span
            class={cn(
              'rounded-sm border border-border px-1 font-mono text-[10px]',
              !canCast() && 'text-muted-foreground',
            )}
          >
            {CIRCLE_LABEL[props.spell.circle]}
          </span>
          {/* basis-32 + wrap: the name claims ~8rem before the chips may share
              the line, so at 390px they wrap below instead of crushing it. */}
          <span class="min-w-0 flex-1 basis-32 truncate text-sm font-medium">
            {props.spell.name}
          </span>
          <span class="ml-auto flex shrink-0 items-center gap-2">
            <span class="hidden text-[10px] uppercase tracking-widest text-muted-foreground sm:inline">
              {SCHOOL_LABEL[props.spell.school]}
            </span>
            <span class="font-mono text-xs text-grimorio-gold">
              {SPELL_BASE_PM_COST[props.spell.circle]} PM
            </span>
            <Show when={bestCd() !== null}>
              <span class="font-mono text-xs text-violet-300">CD {bestCd()}</span>
            </Show>
            <Show when={props.granted} fallback={<LearnedBadge learned={props.learned} />}>
              {(granted) => (
                <span class="rounded-sm border border-border px-1 text-[10px] uppercase tracking-widest">
                  {granted().sourcePower}
                </span>
              )}
            </Show>
          </span>
        </button>
        <Show when={castable()}>
          <CastSpellDialog
            spell={props.spell}
            character={props.character}
            disabled={!canCast()}
            compact
          />
        </Show>
      </div>

      <Show when={open()}>
        <div class="mt-2 space-y-2 border-t border-border pt-2 text-xs">
          <div class="grid gap-1 sm:grid-cols-2">
            <Stat label="Execução" value={props.spell.execution} />
            <Stat label="Alcance" value={props.spell.range} />
            <Stat
              label="Duração"
              value={
                props.spell.duration === 'definida' && props.spell.durationNote
                  ? props.spell.durationNote
                  : props.spell.duration
              }
            />
            <Stat label="Resistência" value={props.spell.resistance ?? '—'} />
            <Stat label="Teste" value={props.spell.saveType} />
            <Stat label="Livro" value={`p${props.spell.bookPage}`} />
          </div>
          <p class="whitespace-pre-line text-foreground">{props.spell.baseEffect}</p>

          <Show when={props.spell.augments.length > 0}>
            <div class="space-y-1">
              <p class="text-[10px] uppercase tracking-widest text-muted-foreground">
                Aprimoramentos
              </p>
              <ul class="space-y-1">
                <For each={props.spell.augments}>
                  {(augment) => (
                    <li class="flex items-start gap-2 rounded-sm border border-border px-2 py-1">
                      <span class="rounded-sm border border-border px-1 font-mono text-[10px]">
                        +{augment.pmCost} PM
                      </span>
                      <span
                        class={cn(
                          'text-[10px] uppercase tracking-widest',
                          augment.kind === 'muda' ? 'text-violet-300' : 'text-emerald-300',
                        )}
                      >
                        {augment.kind}
                      </span>
                      <span class="flex-1 text-foreground">
                        {augment.description}
                        <Show when={augment.classOnly}>
                          {(only) => (
                            <span class="ml-1 italic text-muted-foreground">
                              (apenas {only()})
                            </span>
                          )}
                        </Show>
                        <Show when={augment.requiresCircle !== undefined}>
                          <span class="ml-1 italic text-muted-foreground">
                            (requer {CIRCLE_LABEL[augment.requiresCircle as 0]})
                          </span>
                        </Show>
                      </span>
                    </li>
                  )}
                </For>
              </ul>
            </div>
          </Show>

          <Show when={!canCast() && applicableClasses().length > 0}>
            <p class="flex items-center gap-1 text-[11px] text-foreground">
              <Sparkles aria-hidden="true" class="size-3" />
              Círculo acima do máximo conjurável no nível atual.
            </p>
          </Show>

          {/* A granted spell has no spellbook row to manage. */}
          <Show when={!props.granted}>
            <div class="flex flex-wrap items-center gap-2 border-t border-border pt-2">
              <Show
                when={props.learned}
                fallback={
                  <Button
                    type="button"
                    size="sm"
                    variant="outline"
                    class="h-7 gap-1 text-xs"
                    disabled={pending()}
                    onClick={() => void learn()}
                  >
                    <BookPlus aria-hidden="true" class="size-3.5" />
                    Aprender
                  </Button>
                }
              >
                {(learned) => (
                  <>
                    <Button
                      type="button"
                      size="sm"
                      variant={learned().prepared ? 'default' : 'outline'}
                      class="h-7 gap-1 text-xs"
                      disabled={pending()}
                      onClick={() => void setPrepared(!learned().prepared)}
                    >
                      <Check aria-hidden="true" class="size-3.5" />
                      {learned().prepared ? 'Despreparar' : 'Preparar'}
                    </Button>
                    <Button
                      type="button"
                      size="sm"
                      variant="ghost"
                      class="h-7 gap-1 text-xs text-red-400 hover:bg-red-950/40"
                      disabled={pending()}
                      onClick={() => void unlearn()}
                    >
                      <BookX aria-hidden="true" class="size-3.5" />
                      Esquecer
                    </Button>
                  </>
                )}
              </Show>
            </div>
          </Show>
        </div>
      </Show>
    </div>
  )
}

function LearnedBadge(props: { learned: CharacterSpell | null }) {
  return (
    <Show when={props.learned}>
      {(learned) => (
        <span
          class={cn(
            'rounded-sm px-1 text-[10px] uppercase tracking-widest',
            learned().prepared
              ? 'bg-primary text-primary-foreground'
              : 'bg-muted text-muted-foreground',
          )}
        >
          {learned().prepared ? 'Preparada' : 'Aprendida'}
        </span>
      )}
    </Show>
  )
}

function Stat(props: { label: string; value: string | number }) {
  return (
    <div class="flex items-baseline gap-1">
      <span class="text-[10px] uppercase tracking-widest text-muted-foreground">
        {props.label}
      </span>
      <span class="text-foreground">{props.value}</span>
    </div>
  )
}
