// frontend-solid/src/features/character-sheet/expertise-row.tsx
import { Dumbbell, Star, Trash2 } from 'lucide-solid'
import { For, Show } from 'solid-js'
import {
  ATTRIBUTE_ABBR,
  ATTRIBUTE_KEYS,
  type ExpertiseDef,
  expertiseStateFor,
  trainingBonusForLevel,
} from '@/entities/character/expertise'
import { expertiseFromSheet } from '@/entities/character/computed-sheet'
import type { AttributeKey, Character } from '@/shared/api/api'
import type { ComputedSheetV2 } from '@/shared/lib/computed-sheet-v2'
import { cn } from '@/shared/lib/utils'
import { DialogTrigger } from '@/shared/ui/dialog'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/shared/ui/tooltip'
import { ExpertiseBreakdown } from './expertise-breakdown'
import type { ExpertisePatch } from './expertise-mutations'
import { signed } from './signed'

export type ExpertiseRowProps = {
  character: Character
  def: ExpertiseDef
  sheet: ComputedSheetV2
  onPatch: (patch: ExpertisePatch) => void
  /** Only custom "ofícios" can be deleted. */
  onDelete?: () => void
}

/**
 * One perícia: its total (which opens the breakdown), the name, the trained
 * toggle, the attribute it keys off, and the chips that preview the math.
 */
export function ExpertiseRow(props: ExpertiseRowProps) {
  const state = () => expertiseStateFor(props.character, props.def)
  // Every standard + custom perícia is on the sheet; `?? 0` is only a type guard.
  const entry = () => expertiseFromSheet(props.sheet, props.def.name)
  const total = () => entry()?.total ?? 0
  const halfLevel = () => Math.floor(props.character.level / 2)
  const trainBonus = () => (state().trained ? trainingBonusForLevel(props.character.level) : 0)
  const itemBonus = () => entry()?.itemBonus ?? 0
  const locked = () => !!props.def.trainedOnly && !state().trained

  return (
    <ExpertiseBreakdown
      name={props.def.name}
      total={total()}
      locked={locked()}
      halfLevel={halfLevel()}
      attrAbbr={ATTRIBUTE_ABBR[state().attribute]}
      attrMod={entry()?.attrValue ?? 0}
      trainBonus={trainBonus()}
      itemBonus={itemBonus()}
      contributions={entry()?.itemContributions ?? []}
    >
      <div
        class={cn(
          'flex items-start gap-2.5 rounded-sm border border-grimorio-iron p-2.5 transition-colors hover:border-grimorio-gold/50',
          state().trained && 'bg-[var(--grimorio-panel)]',
        )}
      >
        {/* Both the badge and the name open the breakdown; the toggle, the
            attribute select and delete stay interactive — they are not
            triggers. Kobalte composes via `as=`, where Radix used `asChild`. */}
        <DialogTrigger as={TotalBadge} total={total()} locked={locked()} />
        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-1.5">
            <DialogTrigger
              as="button"
              type="button"
              class="min-w-0 flex-1 truncate text-left text-sm text-foreground hover:underline"
            >
              {props.def.name}
            </DialogTrigger>
            <Show when={props.def.trainedOnly}>
              <TrainedOnlyStar locked={locked()} />
            </Show>
            <TrainedToggle
              trained={state().trained}
              name={props.def.name}
              onToggle={(next) => props.onPatch({ trained: next })}
            />
            <Show when={props.onDelete}>
              {(onDelete) => <DeleteExpertiseButton name={props.def.name} onDelete={onDelete()} />}
            </Show>
          </div>
          <div class="mt-1.5 flex flex-wrap items-center gap-1.5">
            <AttributeSelect
              name={props.def.name}
              value={state().attribute}
              sheet={props.sheet}
              onChange={(attribute) => props.onPatch({ attribute })}
            />
            <Chip label="½lvl" value={String(halfLevel())} />
            <Chip label="treino" value={signed(trainBonus())} />
            <DialogTrigger as="button" type="button" class="inline-flex hover:brightness-110">
              <Chip label="outros" value={signed(itemBonus())} />
            </DialogTrigger>
          </div>
        </div>
      </div>
    </ExpertiseBreakdown>
  )
}

/**
 * The perícia's number, doubling as the breakdown trigger. Locked (trained-only
 * and still untrained) reads as a dashed, dimmed box — the old line-through was
 * illegible on small mono digits.
 */
function TotalBadge(props: { total: number; locked: boolean }) {
  return (
    <button
      {...props}
      type="button"
      aria-label={`Detalhar ${signed(props.total)}`}
      class={cn(
        'flex size-11 shrink-0 items-center justify-center rounded-sm border font-mono text-lg font-bold',
        props.locked
          ? 'border-dashed border-grimorio-iron text-muted-foreground/50'
          : 'border-grimorio-iron bg-[var(--grimorio-panel-raised)] text-grimorio-gold',
      )}
    >
      {signed(props.total)}
    </button>
  )
}

/** Star marking a trained-only perícia; amber while it is locked out. */
function TrainedOnlyStar(props: { locked: boolean }) {
  return (
    <Tooltip>
      <TooltipTrigger
        as="button"
        type="button"
        aria-label="Apenas treinada"
        class="inline-flex shrink-0 cursor-help"
      >
        <Star
          aria-hidden="true"
          class={cn(
            'size-3',
            props.locked
              ? 'fill-amber-500 text-amber-500'
              : 'fill-none text-muted-foreground/60',
          )}
        />
      </TooltipTrigger>
      <TooltipContent>Pode ser usada apenas quando treinada</TooltipContent>
    </Tooltip>
  )
}

function TrainedToggle(props: { trained: boolean; name: string; onToggle: (next: boolean) => void }) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={props.trained}
      aria-label={`${props.name} treinada`}
      onClick={() => props.onToggle(!props.trained)}
      class={cn(
        'inline-flex shrink-0 items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] uppercase tracking-wider transition-colors',
        props.trained
          ? 'border-grimorio-gold/60 text-grimorio-gold'
          : 'border-grimorio-iron text-muted-foreground hover:border-grimorio-gold/40',
      )}
    >
      <Dumbbell aria-hidden="true" class="size-3" />
      Treino
    </button>
  )
}

function DeleteExpertiseButton(props: { name: string; onDelete: () => void }) {
  return (
    <button
      type="button"
      aria-label={`Remover ${props.name}`}
      onClick={() => props.onDelete()}
      class="inline-flex shrink-0 rounded-sm p-1 text-muted-foreground transition-colors hover:text-destructive"
    >
      <Trash2 aria-hidden="true" class="size-3.5" />
    </button>
  )
}

/**
 * Which attribute the perícia keys off. Shows the FINAL modifier (race and item
 * bonuses folded in), not the raw sheet value — otherwise the row disagrees
 * with its own breakdown and total.
 */
function AttributeSelect(props: {
  name: string
  value: AttributeKey
  sheet: ComputedSheetV2
  onChange: (attribute: AttributeKey) => void
}) {
  return (
    <select
      value={props.value}
      onChange={(event) => props.onChange(event.currentTarget.value as AttributeKey)}
      aria-label={`${props.name} atributo`}
      class="h-6 cursor-pointer rounded-full border border-grimorio-iron bg-transparent px-2 font-mono text-[11px] outline-none focus:ring-2 focus:ring-ring"
    >
      <For each={ATTRIBUTE_KEYS}>
        {(key) => (
          <option value={key}>
            {ATTRIBUTE_ABBR[key]} {signed(props.sheet.attributes[key].total)}
          </option>
        )}
      </For>
    </select>
  )
}

function Chip(props: { label: string; value: string }) {
  return (
    <span class="inline-flex items-center gap-1 rounded-full border border-grimorio-iron px-2 py-0.5 text-[10px] text-muted-foreground">
      <span class="uppercase tracking-wider">{props.label}</span>
      <span class="font-mono text-foreground">{props.value}</span>
    </span>
  )
}

// frontend/src/routes/characters/character-sheet/expertise-row.tsx
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { SlidersHorizontal, Star, Trash2 } from 'lucide-react'
import { Button } from '@/shared/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/shared/ui/dialog'
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from '@/shared/ui/tooltip'
import type {
  AttributeKey,
  Character,
  CharacterExpertise,
} from '@/shared/api/api'
import { api } from '@/shared/api/api'
import { invalidateCharacterDependents } from '@/shared/lib/character-cache'
import { expertiseTotalWithItems } from '@/shared/lib/derived'
import type { ExpertiseDef } from '@/shared/lib/expertise'
import {
  ATTRIBUTE_ABBR,
  ATTRIBUTE_KEYS,
  expertiseStateFor,
  trainingBonusForLevel,
} from '@/shared/lib/expertise'
import { characterQueryOptions } from '@/shared/lib/queries'
import {
  accentStrong,
  dimText,
  hoverRow,
  selectClass,
  subtleText,
} from '@/shared/lib/sheet-theme'
import { cn } from '@/shared/lib/utils'
import type { ItemEffects } from '@tormenta20/t20-data'
import { signed } from './signed'

export function ExpertiseRow({
  character,
  def,
  effects,
  onDelete,
}: {
  character: Character
  def: ExpertiseDef
  effects: ItemEffects
  onDelete?: () => void
}) {
  const qc = useQueryClient()
  const queryKey = characterQueryOptions(character.id).queryKey
  const state = expertiseStateFor(character, def)

  type ExpertisePatch = {
    attribute?: AttributeKey
    trained?: boolean
  }

  const mutation = useMutation<
    CharacterExpertise,
    Error,
    ExpertisePatch,
    { previous: Character | undefined }
  >({
    mutationFn: (input) =>
      api.characters.updateExpertise(character.id, { name: def.name, ...input }),
    onMutate: async (input) => {
      await qc.cancelQueries({ queryKey })
      const previous = qc.getQueryData<Character>(queryKey)
      qc.setQueryData<Character>(queryKey, (prev) => {
        if (!prev) return prev
        return {
          ...prev,
          expertises: prev.expertises.map((e) =>
            e.name === def.name ? { ...e, ...input } : e,
          ),
        }
      })
      return { previous }
    },
    onError: (_err, _vars, ctx) => {
      if (ctx?.previous) qc.setQueryData(queryKey, ctx.previous)
    },
    onSuccess: (updated) => {
      qc.setQueryData<Character>(queryKey, (prev) => {
        if (!prev) return prev
        return {
          ...prev,
          expertises: prev.expertises.map((e) =>
            e.name === updated.name ? updated : e,
          ),
        }
      })
      invalidateCharacterDependents(qc, character.id)
    },
  })

  const detail = expertiseTotalWithItems(character, state, effects)
  const total = detail.total
  const halfLevel = Math.floor(character.level / 2)
  const trainBonus = state.trained ? trainingBonusForLevel(character.level) : 0
  const othersDisplay = detail.itemBonus

  const trainedToggle = (
    <input
      type="checkbox"
      className="h-4 w-4 cursor-pointer accent-amber-600 dark:accent-amber-500"
      checked={state.trained}
      onChange={(e) => mutation.mutate({ trained: e.target.checked })}
      aria-label={`${def.name} treinada`}
    />
  )

  const locked = !!def.trainedOnly && !state.trained

  const totalLabel = (
    <span
      className={cn(
        'font-mono text-base font-semibold',
        locked
          ? 'text-zinc-400 line-through dark:text-zinc-600'
          : accentStrong,
      )}
      title={locked ? 'Apenas treinada — não pode ser usada sem treino' : undefined}
    >
      {signed(total)}
    </span>
  )

  const nameNode = (
    <span
      className={cn(
        'flex flex-1 items-center gap-1.5 truncate text-sm',
        locked
          ? 'text-zinc-500 dark:text-zinc-500'
          : 'text-zinc-800 dark:text-zinc-200',
      )}
    >
      <span className="truncate">{def.name}</span>
      {def.trainedOnly && (
        <Tooltip>
          <TooltipTrigger asChild>
            <button
              type="button"
              tabIndex={0}
              aria-label="Apenas treinada"
              className="inline-flex shrink-0 cursor-help"
            >
              <Star
                className={cn(
                  'size-3',
                  locked
                    ? 'fill-amber-500 text-amber-700 dark:fill-amber-400 dark:text-amber-300'
                    : 'fill-zinc-300 text-zinc-500 dark:fill-zinc-700 dark:text-zinc-500',
                )}
              />
            </button>
          </TooltipTrigger>
          <TooltipContent side="top">
            Pode ser usada apenas quando treinada
          </TooltipContent>
        </Tooltip>
      )}
    </span>
  )

  const othersInput = (
    <OthersDisplay
      total={othersDisplay}
      detail={detail}
      expertiseName={def.name}
    />
  )

  return (
    <>
      {/* Mobile: compact row + dialog */}
      <div
        className={cn(
          'flex items-center gap-2 rounded-md px-2 py-1.5 sm:hidden',
          hoverRow,
        )}
      >
        {trainedToggle}
        {nameNode}
        <span className="w-10 text-right">{totalLabel}</span>
        {onDelete && <DeleteExpertiseButton name={def.name} onDelete={onDelete} />}
        <Dialog>
          <DialogTrigger asChild>
            <Button
              type="button"
              variant="ghost"
              size="icon"
              className={cn(
                'size-7',
                subtleText,
                'hover:bg-amber-200/60 hover:text-amber-900 dark:hover:bg-zinc-800/60 dark:hover:text-amber-200',
              )}
              aria-label={`Editar ${def.name}`}
            >
              <SlidersHorizontal className="size-4" />
            </Button>
          </DialogTrigger>
          <DialogContent
            className={cn(
              'w-[calc(100vw-1.5rem)] max-w-[calc(100vw-1.5rem)] p-4 sm:w-full sm:max-w-sm sm:p-6',
              'border-amber-700/40 bg-amber-50 text-zinc-900 dark:border-amber-500/40 dark:bg-zinc-950 dark:text-zinc-100',
            )}
          >
            <DialogHeader>
              <DialogTitle
                className={cn('flex items-center gap-2 font-serif', accentStrong)}
              >
                {def.name}
                {def.trainedOnly && (
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <button
                        type="button"
                        aria-label="Apenas treinada"
                        className="inline-flex cursor-help"
                      >
                        <Star
                          className={cn(
                            'size-4',
                            locked
                              ? 'fill-amber-500 text-amber-700 dark:fill-amber-400 dark:text-amber-300'
                              : 'fill-zinc-300 text-zinc-500 dark:fill-zinc-700 dark:text-zinc-500',
                          )}
                        />
                      </button>
                    </TooltipTrigger>
                    <TooltipContent>
                      Pode ser usada apenas quando treinada
                    </TooltipContent>
                  </Tooltip>
                )}
              </DialogTitle>
            </DialogHeader>
            {def.trainedOnly && !state.trained && (
              <p
                className={cn(
                  'rounded-md border px-3 py-2 text-xs',
                  'border-amber-700/40 bg-amber-100/60 text-amber-900 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200',
                )}
              >
                Esta perícia exige treino para ser usada.
              </p>
            )}
            <div className="space-y-4">
              <div
                className={cn(
                  'flex items-center justify-between rounded-lg border px-4 py-2',
                  'border-amber-700/30 bg-amber-100/70 dark:border-amber-500/30 dark:bg-zinc-900/60',
                )}
              >
                <span
                  className={cn(
                    'text-xs uppercase tracking-widest',
                    subtleText,
                  )}
                >
                  total
                </span>
                <span
                  className={cn(
                    'font-mono text-2xl font-bold',
                    locked
                      ? 'text-zinc-400 line-through dark:text-zinc-500'
                      : accentStrong,
                  )}
                >
                  {signed(total)}
                </span>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <DialogField label="½ nível">
                  <span className="font-mono text-sm text-zinc-800 dark:text-zinc-200">
                    {halfLevel}
                  </span>
                </DialogField>
                <DialogField label="atributo">
                  <select
                    value={state.attribute}
                    onChange={(e) =>
                      mutation.mutate({
                        attribute: e.target.value as AttributeKey,
                      })
                    }
                    className={cn(selectClass, 'h-7 px-2 font-mono text-xs')}
                    aria-label={`${def.name} atributo`}
                  >
                    {ATTRIBUTE_KEYS.map((k) => (
                      <option key={k} value={k}>
                        {ATTRIBUTE_ABBR[k]} {signed(character[k])}
                      </option>
                    ))}
                  </select>
                </DialogField>
                <DialogField label="treino">
                  <div className="flex items-center gap-2">
                    {trainedToggle}
                    <span className="font-mono text-sm text-zinc-800 dark:text-zinc-200">
                      {signed(trainBonus)}
                    </span>
                  </div>
                </DialogField>
                <DialogField label="outros">{othersInput}</DialogField>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>

      {/* Desktop: full breakdown row */}
      <div
        className={cn(
          'hidden items-center gap-2 rounded-md px-2 py-1 sm:flex',
          hoverRow,
        )}
      >
        {trainedToggle}
        {nameNode}
        <span className="w-10 text-right">{totalLabel}</span>
        <span className="w-8 text-center font-mono text-xs text-zinc-700 dark:text-zinc-300">
          {halfLevel}
        </span>
        <select
          value={state.attribute}
          onChange={(e) =>
            mutation.mutate({ attribute: e.target.value as AttributeKey })
          }
          className={cn(selectClass, 'h-7 w-16 px-1 font-mono text-[11px]')}
          aria-label={`${def.name} atributo`}
        >
          {ATTRIBUTE_KEYS.map((k) => (
            <option key={k} value={k}>
              {ATTRIBUTE_ABBR[k]} {signed(character[k])}
            </option>
          ))}
        </select>
        <span className="w-10 text-center font-mono text-xs text-zinc-700 dark:text-zinc-300">
          {signed(trainBonus)}
        </span>
        <div className="w-20">
          <OthersDisplay
            total={othersDisplay}
            detail={detail}
            expertiseName={def.name}
          />
        </div>
        {onDelete ? (
          <DeleteExpertiseButton name={def.name} onDelete={onDelete} />
        ) : (
          <span className="size-7 shrink-0" aria-hidden />
        )}
      </div>
    </>
  )
}

function DeleteExpertiseButton({
  name,
  onDelete,
}: {
  name: string
  onDelete: () => void
}) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="size-7 text-zinc-500 hover:bg-red-100 hover:text-red-700 dark:text-zinc-400 dark:hover:bg-red-950/40 dark:hover:text-red-400"
          onClick={() => {
            if (confirm(`Remover ofício "${name}"?`)) onDelete()
          }}
          aria-label={`Remover ${name}`}
        >
          <Trash2 className="size-3.5" />
        </Button>
      </TooltipTrigger>
      <TooltipContent>Remover ofício</TooltipContent>
    </Tooltip>
  )
}

function OthersDisplay({
  total,
  detail,
  expertiseName,
}: {
  total: number
  detail: ReturnType<typeof expertiseTotalWithItems>
  expertiseName: string
}) {
  const hasContribs = detail.itemContributions.length > 0
  const display = (
    <span
      className={cn(
        'block w-full rounded-md border bg-zinc-100/60 px-2 py-1 text-center font-mono text-xs',
        'border-amber-700/20 text-zinc-700 dark:border-amber-500/20 dark:bg-zinc-900/40 dark:text-zinc-300',
        total === 0 && 'text-zinc-400 dark:text-zinc-600',
        hasContribs &&
          'cursor-pointer hover:bg-amber-100/60 dark:hover:bg-zinc-800/60',
      )}
    >
      {signed(total)}
    </span>
  )
  if (!hasContribs) return display
  return (
    <Dialog>
      <DialogTrigger asChild>
        <button
          type="button"
          className="block w-full"
          aria-label={`Detalhes de Outros — ${expertiseName}`}
        >
          {display}
        </button>
      </DialogTrigger>
      <DialogContent
        className={cn(
          'w-[calc(100vw-1.5rem)] max-w-[calc(100vw-1.5rem)] p-4 sm:w-full sm:max-w-sm sm:p-6',
          'border-amber-700/40 bg-amber-50 text-zinc-900 dark:border-amber-500/40 dark:bg-zinc-950 dark:text-zinc-100',
        )}
      >
        <DialogHeader>
          <DialogTitle
            className={cn('flex items-center gap-2 font-serif', accentStrong)}
          >
            Outros — {expertiseName}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-2 text-sm">
          <ul className="space-y-1">
            {detail.itemContributions.map((c, i) => (
              <li
                key={i}
                className="flex items-center justify-between gap-2 border-b border-amber-700/15 pb-1 dark:border-amber-500/10"
              >
                <span className="truncate">{c.source}</span>
                <span className="shrink-0 font-mono">{signed(c.amount)}</span>
              </li>
            ))}
          </ul>
          <div
            className={cn(
              'flex items-center justify-between rounded-lg border px-3 py-2',
              'border-amber-700/40 bg-amber-100/60 dark:border-amber-500/40 dark:bg-amber-950/30',
            )}
          >
            <span
              className={cn(
                'text-xs uppercase tracking-widest',
                subtleText,
              )}
            >
              Total
            </span>
            <span
              className={cn(
                'font-mono text-2xl font-bold',
                accentStrong,
              )}
            >
              {signed(total)}
            </span>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

function DialogField({
  label,
  children,
}: {
  label: string
  children: React.ReactNode
}) {
  return (
    <div className="flex flex-col gap-1">
      <span className={cn('text-[10px] uppercase tracking-widest', dimText)}>
        {label}
      </span>
      {children}
    </div>
  )
}
