// frontend-solid/src/features/character-sheet/item-form-dialog.tsx
import { type JSX, createSignal } from 'solid-js'
import { z } from 'zod'
import type { CreateItemInput } from '@/shared/api/api'
import type { FieldErrors } from '@/shared/lib/form-errors'
import { Button } from '@/shared/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/shared/ui/dialog'
import { FieldFrame, isInvalid } from '@/shared/ui/field-frame'
import { NumberInput } from '@/shared/ui/number-input'
import { TextField } from '@/shared/ui/text-field'
import {
  ITEM_DIALOG_CONTENT,
  ITEM_DIALOG_TITLE,
  ItemDialogError,
  ItemDialogFooter,
} from './item-dialog-kit'
import { itemWriteMessage } from './item-mutations'

/** A custom inventory item: a name plus a whole-number quantity and a load in
 *  half-slot increments (T20 tracks encumbrance in 0,5-espaço steps). */
const itemFormSchema = z.object({
  name: z.string().trim().min(1, 'Informe um nome.').max(80, 'Máximo 80 caracteres.'),
  quantity: z
    .number()
    .int('Quantidade deve ser inteiro ≥ 1.')
    .min(1, 'Quantidade deve ser inteiro ≥ 1.')
    .max(9999, 'Máximo 9999.'),
  slots: z
    .number()
    .min(0.5, 'Espaços deve ser múltiplo de 0,5 (mínimo 0,5).')
    .max(9999, 'Máximo 9999.')
    .refine((v) => Number.isInteger(v * 2), 'Espaços deve ser múltiplo de 0,5.'),
})

export type ItemFormValues = { name: string; quantity: number; slots: number }

export type ItemFormDialogProps = {
  title: string
  submitLabel: string
  /** Receives the opener; Kobalte has no `asChild`, and every caller brings its
   *  own labelled button. */
  trigger: (open: () => void) => JSX.Element
  /** Seeds the form when editing; leave undefined to create. */
  initial?: ItemFormValues
  onSubmit: (input: CreateItemInput) => Promise<void>
}

/**
 * The form behind both "novo item custom" and per-item edit. Catalog-based
 * items go through the catálogo dialog instead — this one only ever carries
 * name/quantity/slots.
 *
 * @example
 * <ItemFormDialog title="Novo item" submitLabel="Adicionar"
 *   trigger={(open) => <Button onClick={open}>Custom</Button>}
 *   onSubmit={(input) => actions().add(input)} />
 */
export function ItemFormDialog(props: ItemFormDialogProps) {
  const [open, setOpen] = createSignal(false)
  const [name, setName] = createSignal(props.initial?.name ?? '')
  const [quantity, setQuantity] = createSignal(props.initial?.quantity ?? 1)
  const [slots, setSlots] = createSignal(props.initial?.slots ?? 1)
  const [fieldErrors, setFieldErrors] = createSignal<FieldErrors>({})
  const [formError, setFormError] = createSignal<string | null>(null)
  const [pending, setPending] = createSignal(false)

  /** Reopening must not show the last attempt's leftovers. */
  const reset = () => {
    setName(props.initial?.name ?? '')
    setQuantity(props.initial?.quantity ?? 1)
    setSlots(props.initial?.slots ?? 1)
    setFieldErrors({})
    setFormError(null)
  }

  const submit = async (event: SubmitEvent) => {
    event.preventDefault()
    setFormError(null)
    const parsed = itemFormSchema.safeParse({
      name: name(),
      quantity: quantity(),
      slots: slots(),
    })
    if (!parsed.success) {
      setFieldErrors(z.flattenError(parsed.error).fieldErrors as FieldErrors)
      return
    }
    setFieldErrors({})
    setPending(true)
    try {
      await props.onSubmit(parsed.data)
      setOpen(false)
      reset()
    } catch (failure) {
      setFormError(itemWriteMessage(failure, 'Não foi possível salvar o item.'))
    } finally {
      setPending(false)
    }
  }

  return (
    <>
      {props.trigger(() => {
        reset()
        setOpen(true)
      })}
      <Dialog open={open()} onOpenChange={setOpen}>
        <DialogContent class={ITEM_DIALOG_CONTENT}>
          <DialogHeader>
            <DialogTitle class={ITEM_DIALOG_TITLE}>{props.title}</DialogTitle>
          </DialogHeader>
          <form class="space-y-4" onSubmit={submit} noValidate>
            <TextField
              name="item-name"
              label="Nome"
              value={name()}
              onInput={setName}
              errors={fieldErrors().name}
            />
            <div class="grid grid-cols-2 gap-3">
              <FieldFrame name="item-quantity" label="Quantidade" errors={fieldErrors().quantity}>
                <NumberInput
                  id="item-quantity"
                  value={quantity()}
                  onChange={setQuantity}
                  min={1}
                  max={9999}
                  step={1}
                  aria-invalid={isInvalid(fieldErrors().quantity)}
                />
              </FieldFrame>
              <FieldFrame
                name="item-slots"
                label="Espaços"
                hint="Múltiplo de 0,5 (ex.: 0,5 / 1 / 1,5)."
                errors={fieldErrors().slots}
              >
                <NumberInput
                  id="item-slots"
                  value={slots()}
                  onChange={setSlots}
                  min={0.5}
                  max={9999}
                  step={0.5}
                  aria-invalid={isInvalid(fieldErrors().slots)}
                />
              </FieldFrame>
            </div>
            <ItemDialogError message={formError()} />
            <ItemDialogFooter>
              <Button type="button" variant="outline" onClick={() => setOpen(false)}>
                Cancelar
              </Button>
              <Button type="submit" disabled={pending()}>
                {pending() ? 'Salvando…' : props.submitLabel}
              </Button>
            </ItemDialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </>
  )
}

// frontend/src/routes/characters/character-sheet/item-form-dialog.tsx
import { type ReactNode, useState } from 'react'
import { Info } from 'lucide-react'
import { getCatalogItem } from '@tormenta20/t20-data'
import { Button } from '@/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { NumberInput } from '@/components/ui/number-input'
import type {
  CharacterItem,
  CreateItemInput,
} from '@/lib/api'
import { accentStrong, dimText, subtleText } from '@/lib/sheet-theme'
import { cn } from '@/lib/utils'
import { CatalogInfoBody } from './catalog-info-body'
import { formatLoad } from './item-describe'

/**
 * Read-only info dialog for a single inventory row. Falls back to a
 * "custom item" message when the row has no catalog link.
 */
export function ItemInfoDialog({ item }: { item: CharacterItem }) {
  const catalog = item.catalogId ? getCatalogItem(item.catalogId) : undefined
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className={cn(
            'size-7',
            subtleText,
            'hover:bg-amber-200/60 hover:text-amber-900 dark:hover:bg-zinc-800/60 dark:hover:text-amber-200',
          )}
          aria-label={`Informações de ${item.name}`}
        >
          <Info className="size-3.5" />
        </Button>
      </DialogTrigger>
      <DialogContent
        className={cn(
          'w-[calc(100vw-1.5rem)] max-w-[calc(100vw-1.5rem)] p-4 sm:w-full sm:max-w-md sm:p-6',
          'border-amber-700/40 bg-amber-50 text-zinc-900 dark:border-amber-500/40 dark:bg-zinc-950 dark:text-zinc-100',
        )}
      >
        <DialogHeader>
          <DialogTitle className={cn('font-serif', accentStrong)}>
            {item.name}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-3">
          <div
            className={cn(
              'rounded-md border px-3 py-2 text-xs',
              'border-amber-700/30 bg-amber-100/70 dark:border-amber-500/30 dark:bg-zinc-900/60',
            )}
          >
            <p>
              quantidade <span className="font-mono">{item.quantity}</span> •
              espaços <span className="font-mono">{formatLoad(item.slots)}</span>{' '}
              • total{' '}
              <span className={cn('font-mono font-semibold', accentStrong)}>
                {formatLoad(item.quantity * item.slots)}
              </span>
            </p>
            <p className={dimText}>
              equipado:{' '}
              {item.equipped
                ? item.equipped === 'wielded'
                  ? '1 mão'
                  : item.equipped === 'wielded2'
                    ? '2 mãos'
                    : 'vestido'
                : '—'}
            </p>
          </div>
          {catalog ? (
            <CatalogInfoBody catalog={catalog} />
          ) : (
            <p className={cn('text-xs', dimText)}>
              Item customizado, sem dados de catálogo.
            </p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

/**
 * Form dialog used for both "novo item custom" (create) and per-item
 * edit. `initial` seeds the form; leave undefined for create. The
 * shape passes name/quantity/slots — catalog-based items go through
 * `AddCatalogItemDialog` instead.
 */
export function ItemFormDialog({
  title,
  submitLabel,
  trigger,
  initial,
  onSubmit,
}: {
  title: string
  submitLabel: string
  trigger: ReactNode
  initial?: Partial<CreateItemInput>
  onSubmit: (input: CreateItemInput, onError: (e: Error) => void) => void
}) {
  const [open, setOpen] = useState(false)
  const [name, setName] = useState(initial?.name ?? '')
  const [quantity, setQuantity] = useState<string>(String(initial?.quantity ?? 1))
  const [slots, setSlots] = useState<string>(String(initial?.slots ?? 1))
  const [error, setError] = useState<string | null>(null)

  const reset = () => {
    setName(initial?.name ?? '')
    setQuantity(String(initial?.quantity ?? 1))
    setSlots(String(initial?.slots ?? 1))
    setError(null)
  }

  const apply = () => {
    const trimmed = name.trim()
    const qty = Number(quantity)
    const sl = Number(slots)
    if (!trimmed) {
      setError('Informe um nome.')
      return
    }
    if (!Number.isInteger(qty) || qty < 1) {
      setError('Quantidade deve ser inteiro ≥ 1.')
      return
    }
    if (!Number.isFinite(sl) || sl < 0.5 || !Number.isInteger(sl * 2)) {
      setError('Espaços deve ser múltiplo de 0,5 (mínimo 0,5).')
      return
    }
    onSubmit({ name: trimmed, quantity: qty, slots: sl }, (e) =>
      setError(e.message),
    )
    setOpen(false)
    reset()
  }

  return (
    <Dialog
      open={open}
      onOpenChange={(o) => {
        setOpen(o)
        if (!o) reset()
      }}
    >
      <DialogTrigger asChild>{trigger}</DialogTrigger>
      <DialogContent
        className={cn(
          'w-[calc(100vw-1.5rem)] max-w-[calc(100vw-1.5rem)] p-4 sm:w-full sm:max-w-sm sm:p-6',
          'border-amber-700/40 bg-amber-50 text-zinc-900 dark:border-amber-500/40 dark:bg-zinc-950 dark:text-zinc-100',
        )}
      >
        <DialogHeader>
          <DialogTitle className={cn('font-serif', accentStrong)}>
            {title}
          </DialogTitle>
        </DialogHeader>
        <div className="space-y-4">
          <div className="space-y-1">
            <span className={cn('text-[10px] uppercase tracking-widest', dimText)}>
              nome
            </span>
            <Input
              value={name}
              onChange={(e) => {
                setName(e.target.value)
                if (error) setError(null)
              }}
              placeholder="Ex: Espada longa"
              autoFocus
              maxLength={80}
            />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <span
                className={cn('text-[10px] uppercase tracking-widest', dimText)}
              >
                quantidade
              </span>
              <NumberInput
                value={quantity}
                onChange={(v) => setQuantity(String(v))}
                min={1}
                max={9999}
                step={1}
                aria-label="Quantidade"
              />
            </div>
            <div className="space-y-1">
              <span
                className={cn('text-[10px] uppercase tracking-widest', dimText)}
              >
                espaços
              </span>
              <NumberInput
                value={slots}
                onChange={(v) => setSlots(String(v))}
                min={0.5}
                max={9999}
                step={0.5}
                aria-label="Espaços"
              />
            </div>
          </div>
          <p className={cn('text-[11px]', dimText)}>
            Espaços é múltiplo de 0,5 (ex.: 0,5 / 1 / 1,5).
          </p>
          {error && (
            <p className="text-xs text-destructive" role="alert">
              {error}
            </p>
          )}
          <div className="flex justify-end gap-2">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancelar
            </Button>
            <Button type="button" onClick={apply}>
              {submitLabel}
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
