// frontend/src/pages/campaigns/campaign-detail-page.tsx
import { getRouteApi, useNavigate } from '@tanstack/react-router'
import { useQuery } from '@tanstack/react-query'
import { CalendarClock } from 'lucide-react'
import { SceneShell } from '@/shared/layout/scene-shell'
import { useSfx } from '@/shared/lib/use-sfx'
import { Skeleton } from '@/shared/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/shared/ui/tabs'
import { Card, CardContent } from '@/shared/ui/card'
import { campaignQueryOptions, campaignMembersQueryOptions } from '@/entities/campaign/queries'
import { campaignSessionsQueryOptions } from '@/entities/session/queries'
import { CampaignHeaderCard } from '@/features/campaign-manage/header-card'
import { CampaignOverview } from '@/features/campaign-manage/campaign-overview'
import { DeleteCampaignButton } from '@/features/campaign-manage/delete-campaign-button'
import { MembersCard } from '@/features/campaign-manage/members-card'
import { SessionsCard } from '@/features/campaign-manage/sessions-card'

const routeApi = getRouteApi('/campaigns/$id/')

type CampaignTab = 'visao' | 'sessoes' | 'membros' | 'config'

/**
 * Campaign detail (GM + player) as a grimório scene (ALE-58): a full-screen
 * SceneShell (back → Crônicas) over the name + status subtitle and the
 * Visão geral / Sessões / Membros / Config tabs. The active tab lives in
 * `?tab=` so it deep-links and survives the back button. Config (edit + delete)
 * is GM-only. The live-session route (`/sessions/$sid`) stays its own bare
 * match-mode scene; only this index page is the detail scene.
 */
export function CampaignDetailPage() {
  const { id } = routeApi.useParams()
  const { tab } = routeApi.useSearch()
  const navigate = useNavigate()
  const sfx = useSfx()
  const campaignId = Number(id)
  const campaign = useQuery(campaignQueryOptions(campaignId))
  const sessions = useQuery(campaignSessionsQueryOptions(campaignId))
  const members = useQuery(campaignMembersQueryOptions(campaignId))
  const isGm = campaign.data?.role === 'gm'
  const activeSession = sessions.data?.find((s) => s.status === 'active')
  const playerCount =
    members.data?.filter((m) => m.role === 'player').length ?? 0

  const current: CampaignTab = isTab(tab) ? tab : 'visao'
  const goToTab = (next: CampaignTab) =>
    navigate({ to: '.', search: { tab: next }, replace: true })
  const back = () => {
    sfx('select')
    navigate({ to: '/campaigns' })
  }

  if (campaign.isLoading)
    return (
      <SceneShell dense title="Campanha" onBack={back}>
        <div className="mx-auto w-full max-w-5xl space-y-4">
          <Skeleton className="h-8 w-56" />
          <Skeleton className="h-40 w-full" />
        </div>
      </SceneShell>
    )
  if (campaign.isError)
    return (
      <SceneShell dense title="Campanha" onBack={back}>
        <p className="text-destructive">{(campaign.error as Error).message}</p>
      </SceneShell>
    )
  if (!campaign.data) return null

  return (
    <SceneShell
      dense
      title={campaign.data.name}
      onBack={back}
      onEnter={() => sfx('transition')}
    >
      <div className="mx-auto w-full max-w-5xl space-y-5">
        <p className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
          <span>{isGm ? 'Mestrando' : 'Jogando'}</span>
          <span aria-hidden>·</span>
          <span className="flex items-center gap-1">
            <CalendarClock className="size-3" />
            Criada em{' '}
            {new Date(campaign.data.createdAt).toLocaleDateString('pt-BR')}
          </span>
          <span aria-hidden>·</span>
          <span>
            {playerCount} {playerCount === 1 ? 'jogador' : 'jogadores'}
          </span>
          {activeSession && (
            <>
              <span aria-hidden>·</span>
              <span className="flex items-center gap-1 font-medium text-foreground">
                <span className="size-2 rounded-full bg-[color:var(--hp-full)]" />
                Sessão {activeSession.sessionNumber} ativa
              </span>
            </>
          )}
        </p>

        <Tabs value={current} onValueChange={(v) => goToTab(v as CampaignTab)}>
          <TabsList className="max-w-full self-start overflow-x-auto [&>button]:shrink-0">
            <TabsTrigger value="visao">Visão geral</TabsTrigger>
            <TabsTrigger value="sessoes">Sessões</TabsTrigger>
            <TabsTrigger value="membros">Membros</TabsTrigger>
            {isGm && <TabsTrigger value="config">Config</TabsTrigger>}
          </TabsList>

          <TabsContent value="visao">
            <CampaignOverview
              campaignId={campaignId}
              isGm={isGm}
              onGoToTab={goToTab}
            />
          </TabsContent>
          <TabsContent value="sessoes">
            <SessionsCard campaignId={campaignId} isGm={isGm} />
          </TabsContent>
          <TabsContent value="membros">
            <MembersCard campaignId={campaignId} isGm={isGm} />
          </TabsContent>
          {isGm && (
            <TabsContent value="config" className="space-y-6">
              <CampaignHeaderCard campaign={campaign.data} />
              <Card className="border-destructive/40">
                <CardContent className="flex flex-wrap items-center justify-between gap-3 pt-6">
                  <div>
                    <p className="font-medium">Excluir campanha</p>
                    <p className="text-xs text-muted-foreground">
                      Remove todas as sessões e membros. Não pode ser desfeito.
                    </p>
                  </div>
                  <DeleteCampaignButton campaign={campaign.data} />
                </CardContent>
              </Card>
            </TabsContent>
          )}
        </Tabs>
      </div>
    </SceneShell>
  )
}

function isTab(v: string | undefined): v is CampaignTab {
  return v === 'visao' || v === 'sessoes' || v === 'membros' || v === 'config'
}

// frontend-solid/src/pages/campaigns/campaign-detail-page.tsx
import { useQuery } from '@tanstack/solid-query'
import { getRouteApi, useNavigate } from '@tanstack/solid-router'
import { Show } from 'solid-js'
import { campaignMembersQueryOptions, campaignQueryOptions } from '@/entities/campaign/queries'
import { campaignSessionsQueryOptions } from '@/entities/session/queries'
import {
  CAMPAIGN_TABS,
  type CampaignTab,
  CampaignTome,
  isCampaignTab,
} from '@/features/campaign-manage/campaign-tome'
import { SceneShell } from '@/shared/layout/scene-shell'
import { createSceneNav } from '@/shared/lib/scene-nav'
import { createSfx } from '@/shared/lib/sfx'
import { useUi } from '@/shared/stores/ui-context'
import { Skeleton } from '@/shared/ui/skeleton'

const routeApi = getRouteApi('/campaigns/$id/')

/**
 * Campaign detail as a grimório scene, redesigned into an open tome: the
 * SceneShell owns the back-to-Crônicas control; the CampaignTome renders the
 * chronicle as a book. The active tab lives in `?tab=` so it deep-links and
 * survives the back button.
 *
 * The React version could NOT read the tab straight from the URL: its comment
 * explains that the router's state is a `useSyncExternalStore` React can't
 * defer, so every switch ran as one synchronous navigation and felt slow. It
 * kept a local `useState` mirror for the instant paint plus TWO effects — one
 * adopting the URL, one debouncing the URL write by 250ms — and the tab lived
 * in two places at once.
 *
 * Here the search param IS the state. No mirror, no debounce, no effects: with
 * no re-render to schedule, a navigation only updates what actually reads it.
 */
export function CampaignDetailPage() {
  const params = routeApi.useParams()
  const search = routeApi.useSearch()
  const navigate = useNavigate()
  const ui = useUi()
  const sfx = createSfx(ui)

  const campaignId = () => Number(params().id)
  const campaign = useQuery(() => campaignQueryOptions(campaignId()))
  const sessions = useQuery(() => campaignSessionsQueryOptions(campaignId()))
  const members = useQuery(() => campaignMembersQueryOptions(campaignId()))

  const isGm = () => campaign.data?.role === 'gm'
  const activeSession = () => sessions.data?.find((s) => s.status === 'active')
  const playerCount = () => members.data?.filter((m) => m.role === 'player').length ?? 0

  const tab = (): CampaignTab => {
    const fromUrl = search().tab
    return isCampaignTab(fromUrl) ? fromUrl : 'visao'
  }

  const goToTab = (next: CampaignTab) => {
    if (next === tab()) return
    sfx('select')
    navigate({ to: '.', search: { tab: next }, replace: true })
  }

  const back = () => {
    sfx('back')
    navigate({ to: '/campaigns' })
  }

  const resume = () => {
    const session = activeSession()
    if (!session) return
    sfx('select')
    navigate({
      to: '/campaigns/$id/sessions/$sid',
      params: { id: String(campaignId()), sid: String(session.id) },
    })
  }

  // Game-like walk through the chronicle via the shared scene-nav grammar:
  // arrows move the focus cursor by layout within a region and cross rail ↔
  // header ↔ content at the edges; PageUp/PageDown are the section bumpers;
  // Esc pops content → rail → back to the book.
  const cycleSection = (delta: number) => {
    const index = Math.max(0, CAMPAIGN_TABS.indexOf(tab()))
    goToTab(CAMPAIGN_TABS[(index + delta + CAMPAIGN_TABS.length) % CAMPAIGN_TABS.length])
  }

  createSceneNav({
    root: () => document.querySelector<HTMLElement>('[data-tome-root]'),
    onEscape: back,
    bumpers: { prev: () => cycleSection(-1), next: () => cycleSection(1) },
    sfx,
    active: () => !campaign.isLoading && !!campaign.data,
  })

  return (
    <Show
      when={!campaign.isLoading}
      fallback={
        <SceneShell dense onBack={back}>
          <div class="w-full space-y-4">
            <Skeleton class="h-8 w-56" />
            <Skeleton class="h-56 w-full" />
          </div>
        </SceneShell>
      }
    >
      <Show
        when={campaign.data}
        fallback={
          <SceneShell dense onBack={back}>
            <p class="text-destructive">{(campaign.error as Error | null)?.message}</p>
          </SceneShell>
        }
      >
        {(data) => (
          <SceneShell dense onBack={back} onEnter={() => sfx('open')}>
            <CampaignTome
              campaign={data()}
              campaignId={campaignId()}
              isGm={isGm()}
              activeSession={activeSession()}
              playerCount={playerCount()}
              current={tab()}
              onTab={goToTab}
              onResume={resume}
            />
          </SceneShell>
        )}
      </Show>
    </Show>
  )
}
